// ══════════════════════════════════════════════════════════════════════
// BANCO OFICIAL COMPLETO — Guardia Civil 2021-2025
// Ortografía: 75 frases | Gramática: 55 preguntas | Inglés: 120 preguntas
// ══════════════════════════════════════════════════════════════════════

// ── HELPER: Aleatorizar array ──
function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// ── HELPER: Coger N elementos aleatorios ──
function pickRandom(arr, n) {
  return shuffle(arr).slice(0, n);
}

// ══════════════════════════════════════════════════════════════════════
// BANCO ORTOGRAFÍA — Frases reales de exámenes oficiales
// ══════════════════════════════════════════════════════════════════════
const TODAS_FRASES_ORT = [
  // 2021 – 1A
  { f:"2021-1A", texto_previo:"Se a ordenado la", A:{word:"incoación",error:false}, texto_AB:"de un expediente por", B:{word:"coaccionar",error:false}, texto_BC:"a la", C:{word:"bíctima",error:true}, texto_CD:".", D:{word:"",error:false}, texto_post:"", explicacion:"C: 'bíctima' → 'víctima' (v, no b)." },
  { f:"2021-1A", texto_previo:"He", A:{word:"rehusado",error:false}, texto_AB:"", B:{word:"usar",error:false}, texto_BC:"la", C:{word:"cerragería",error:true}, texto_CD:"de", D:{word:"hacero",error:true}, texto_post:".", explicacion:"C: 'cerragería' → 'cerrajería' (ll). D: 'hacero' → 'acero' (sin h)." },
  { f:"2021-1A", texto_previo:"¿Por que vienes", A:{word:"sólo",error:false}, texto_AB:"? Te", B:{word:"dijimos",error:false}, texto_BC:"que", C:{word:"trageses",error:true}, texto_CD:"un acompañante.", D:{word:"",error:false}, texto_post:"", explicacion:"C: 'trageses' → 'trajeses' (j; subjuntivo de traer)." },
  { f:"2021-1A", texto_previo:"Cada", A:{word:"indivíduo",error:true}, texto_AB:"tiene sus", B:{word:"fovias",error:true}, texto_BC:", sus", C:{word:"manías",error:false}, texto_CD:"y sus", D:{word:"anhelos",error:false}, texto_post:".", explicacion:"A: 'indivíduo' → 'individuo' (sin tilde; es esdrújula en -duo). B: 'fovias' → 'fobias' (b)." },
  { f:"2021-1A", texto_previo:"Los", A:{word:"espectadores",error:false}, texto_AB:"", B:{word:"obserbaban",error:true}, texto_BC:"", C:{word:"espectantes",error:true}, texto_CD:"la", D:{word:"funcion",error:true}, texto_post:".", explicacion:"B: 'obserbaban' → 'observaban' (v). C: 'espectantes' → 'expectantes'. D: 'funcion' → 'función' (tilde)." },
  { f:"2021-1A", texto_previo:"La", A:{word:"terápia",error:true}, texto_AB:"que", B:{word:"recomiénda",error:true}, texto_BC:"este", C:{word:"terapéuta",error:true}, texto_CD:"no es la que nos", D:{word:"recomendasteis",error:false}, texto_post:".", explicacion:"A: 'terápia' → 'terapia'. B: 'recomiénda' → 'recomienda'. C: 'terapéuta' → 'terapeuta' (sin tilde)." },
  { f:"2021-1A", texto_previo:"", A:{word:"Cojió",error:true}, texto_AB:"la", B:{word:"gabardina",error:false}, texto_BC:", el", C:{word:"paragüas",error:true}, texto_CD:"y las", D:{word:"votas",error:true}, texto_post:", y se marchó.", explicacion:"A: 'Cojió' → 'Cogió' (g). C: 'paragüas' → 'paraguas'. D: 'votas' → 'botas' (b)." },
  { f:"2021-1A", texto_previo:"", A:{word:"Atribulleron",error:true}, texto_AB:"las", B:{word:"hueyas",error:true}, texto_BC:"a los", C:{word:"reenes",error:true}, texto_CD:"que", D:{word:"huyeron",error:false}, texto_post:".", explicacion:"A: 'atribulleron' → 'atribuyeron'. B: 'hueyas' → 'huellas'. C: 'reenes' → 'rehenes' (h)." },
  { f:"2021-1A", texto_previo:"", A:{word:"Infringió",error:false}, texto_AB:"varios", B:{word:"preceptos",error:false}, texto_BC:"de la", C:{word:"normativa",error:false}, texto_CD:"", D:{word:"vigente",error:false}, texto_post:".", explicacion:"Todas correctas." },
  { f:"2021-1A", texto_previo:"El movimiento", A:{word:"sismico",error:true}, texto_AB:"", B:{word:"provocó",error:false}, texto_BC:"numerosos", C:{word:"vaibenes",error:true}, texto_CD:"en la", D:{word:"hatalaya",error:true}, texto_post:".", explicacion:"A: 'sismico' → 'sísmico'. C: 'vaibenes' → 'vaivenes'. D: 'hatalaya' → 'atalaya' (sin h)." },
  // 2021 – 2A
  { f:"2021-2A", texto_previo:"", A:{word:"Cojed",error:true}, texto_AB:"", B:{word:"ésas",error:false}, texto_BC:"", C:{word:"erramientas",error:true}, texto_CD:"y", D:{word:"marcháos",error:true}, texto_post:".", explicacion:"A: 'Cojed' → 'Coged'. C: 'erramientas' → 'herramientas'. D: 'marcháos' → 'marchaos' (sin tilde)." },
  { f:"2021-2A", texto_previo:"La", A:{word:"extraordinaria",error:false}, texto_AB:"", B:{word:"inflación",error:false}, texto_BC:"", C:{word:"provocó",error:false}, texto_CD:"un efecto", D:{word:"devastador",error:false}, texto_post:".", explicacion:"Todas correctas." },
  { f:"2021-2A", texto_previo:"La", A:{word:"bulimia",error:false}, texto_AB:"y la", B:{word:"anorecsia",error:true}, texto_BC:"están", C:{word:"relazionadas",error:true}, texto_CD:"con la", D:{word:"injesta",error:true}, texto_post:"de alimentos.", explicacion:"B: 'anorecsia' → 'anorexia'. C: 'relazionadas' → 'relacionadas'. D: 'injesta' → 'ingesta' (g)." },
  { f:"2021-2A", texto_previo:"El", A:{word:"vigésimo",error:false}, texto_AB:"punto", B:{word:"prohibe",error:false}, texto_BC:"", C:{word:"verter",error:false}, texto_CD:"agua", D:{word:"hirbiendo",error:true}, texto_post:".", explicacion:"D: 'hirbiendo' → 'hirviendo' (v)." },
  { f:"2021-2A", texto_previo:"El", A:{word:"abanderado",error:false}, texto_AB:"sintió", B:{word:"verguenza",error:true}, texto_BC:"al", C:{word:"enarvolar",error:true}, texto_CD:"una bandera", D:{word:"extrangera",error:true}, texto_post:".", explicacion:"B: 'verguenza' → 'vergüenza'. C: 'enarvolar' → 'enarbolar'. D: 'extrangera' → 'extranjera' (j)." },
  { f:"2021-2A", texto_previo:"La", A:{word:"autopsia",error:false}, texto_AB:"", B:{word:"rebeló",error:true}, texto_BC:"las", C:{word:"graves",error:false}, texto_CD:"lesiones que le habían", D:{word:"infligido",error:false}, texto_post:".", explicacion:"B: 'rebeló' → 'reveló' (v); 'rebeló' significaría que se rebeló." },
  { f:"2021-2A", texto_previo:"Hallaron la", A:{word:"hosamenta",error:true}, texto_AB:"de una", B:{word:"hiena",error:false}, texto_BC:"en una", C:{word:"oquedad",error:false}, texto_CD:".", D:{word:"",error:false}, texto_post:"", explicacion:"A: 'hosamenta' → 'osamenta' (sin h)." },
  { f:"2021-2A", texto_previo:"El", A:{word:"reo",error:false}, texto_AB:"necesita un testigo que", B:{word:"avale",error:false}, texto_BC:"su", C:{word:"versión",error:false}, texto_CD:"de los", D:{word:"hechos",error:false}, texto_post:".", explicacion:"Todas correctas." },
  { f:"2021-2A", texto_previo:"Los", A:{word:"convoyes",error:false}, texto_AB:"llegaron", B:{word:"finalménte",error:true}, texto_BC:"a una", C:{word:"ámplia",error:true}, texto_CD:"", D:{word:"esplanada",error:true}, texto_post:".", explicacion:"B: 'finalménte' → 'finalmente'. C: 'ámplia' → 'amplia'. D: 'esplanada' → 'explanada'." },
  { f:"2021-2A", texto_previo:"Tras echarle una", A:{word:"ojeada",error:false}, texto_AB:"a la", B:{word:"documentacion",error:true}, texto_BC:", vi que la", C:{word:"enviásteis",error:false}, texto_CD:"sin", D:{word:"reyenar",error:true}, texto_post:".", explicacion:"B: 'documentacion' → 'documentación'. D: 'reyenar' → 'rellenar' (ll)." },
  // 2022 – 1A
  { f:"2022-1A", texto_previo:"Tras superar su", A:{word:"adición",error:false}, texto_AB:"a los", B:{word:"opíaceos",error:true}, texto_BC:"y a la", C:{word:"cocaina",error:true}, texto_CD:"", D:{word:"rehízo",error:false}, texto_post:"su vida.", explicacion:"B: 'opíaceos' → 'opiáceos' (tilde en á). C: 'cocaina' → 'cocaína' (tilde)." },
  { f:"2022-1A", texto_previo:"Los", A:{word:"lejionarios",error:true}, texto_AB:"se", B:{word:"acogen",error:false}, texto_BC:"a su", C:{word:"liturjia",error:true}, texto_CD:"de una forma", D:{word:"prodigiosa",error:false}, texto_post:".", explicacion:"A: 'lejionarios' → 'legionarios' (g). C: 'liturjia' → 'liturgia' (g)." },
  { f:"2022-1A", texto_previo:"Le", A:{word:"reconvinieron",error:false}, texto_AB:"por su carácter", B:{word:"extremadamente",error:false}, texto_BC:"", C:{word:"huraño",error:false}, texto_CD:".", D:{word:"",error:false}, texto_post:"", explicacion:"Todas correctas." },
  { f:"2022-1A", texto_previo:"El", A:{word:"ventrílocuo",error:false}, texto_AB:"se", B:{word:"untó",error:false}, texto_BC:"un", C:{word:"hungüento",error:true}, texto_CD:"en los", D:{word:"lavios",error:true}, texto_post:".", explicacion:"C: 'hungüento' → 'ungüento' (sin h). D: 'lavios' → 'labios' (b)." },
  { f:"2022-1A", texto_previo:"", A:{word:"Sorvía",error:true}, texto_AB:"lentamente su", B:{word:"té",error:false}, texto_BC:"mientras leía la noticia de la", C:{word:"absolución",error:false}, texto_CD:"de su", D:{word:"visnieto",error:true}, texto_post:".", explicacion:"A: 'Sorvía' → 'Sorbía' (b). D: 'visnieto' → 'bisnieto' (b)." },
  // 2022 – 2A
  { f:"2022-2A", texto_previo:"Los", A:{word:"herejes",error:false}, texto_AB:"", B:{word:"adugeron",error:true}, texto_BC:"que nuestra", C:{word:"teología",error:false}, texto_CD:"es muy", D:{word:"demagójica",error:true}, texto_post:".", explicacion:"B: 'adugeron' → 'adujeron' (j). D: 'demagójica' → 'demagógica' (g)." },
  { f:"2022-2A", texto_previo:"Se mostraban", A:{word:"titubeantes",error:false}, texto_AB:"y", B:{word:"cohibidos",error:false}, texto_BC:"debido a las", C:{word:"vejaciones",error:false}, texto_CD:"que", D:{word:"sufriéron",error:true}, texto_post:".", explicacion:"D: 'sufriéron' → 'sufrieron' (sin tilde en pretéritos en -eron)." },
  { f:"2022-2A", texto_previo:"", A:{word:"Fué",error:true}, texto_AB:"un", B:{word:"bicepresidente",error:true}, texto_BC:"muy", C:{word:"longebo",error:true}, texto_CD:"que se", D:{word:"mantubo",error:true}, texto_post:"mucho tiempo en el poder.", explicacion:"A: 'Fué' → 'Fue' (monosílabo). B: 'bicepresidente' → 'vicepresidente'. C: 'longebo' → 'longevo'. D: 'mantubo' → 'mantuvo' (v)." },
  { f:"2022-2A", texto_previo:"", A:{word:"Llebaba",error:true}, texto_AB:"su", B:{word:"profesion",error:true}, texto_BC:"con absoluta", C:{word:"discrección",error:true}, texto_CD:"y", D:{word:"ateniéndose",error:false}, texto_post:"a las leyes.", explicacion:"A: 'Llebaba' → 'Llevaba' (ll y v). B: 'profesion' → 'profesión'. C: 'discrección' → 'discreción' (una c)." },
  { f:"2022-2A", texto_previo:"El mercado", A:{word:"bursátil",error:false}, texto_AB:"es", B:{word:"versátil",error:false}, texto_BC:",", C:{word:"fluctuante",error:false}, texto_CD:"y", D:{word:"discontínuo",error:true}, texto_post:".", explicacion:"D: 'discontínuo' → 'discontinuo' (sin tilde; llana en vocal)." },
  // 2022 – 3A
  { f:"2022-3A", texto_previo:"Le", A:{word:"estirparon",error:true}, texto_AB:"la", B:{word:"besícula",error:true}, texto_BC:"y el", C:{word:"bazo",error:false}, texto_CD:"a las", D:{word:"dieciseis",error:true}, texto_post:"horas.", explicacion:"A: 'estirparon' → 'extirparon'. B: 'besícula' → 'vesícula' (v). D: 'dieciseis' → 'dieciséis'." },
  { f:"2022-3A", texto_previo:"", A:{word:"Asistían",error:false}, texto_AB:"con", B:{word:"desazón",error:false}, texto_BC:"al", C:{word:"desahucio",error:false}, texto_CD:"de los", D:{word:"indigentes",error:false}, texto_post:".", explicacion:"Todas correctas." },
  { f:"2022-3A", texto_previo:"El", A:{word:"jinete",error:false}, texto_AB:"", B:{word:"expoleaba",error:true}, texto_BC:"con", C:{word:"violéncia",error:true}, texto_CD:"a la", D:{word:"yegüa",error:false}, texto_post:".", explicacion:"B: 'expoleaba' → 'espoleaba'. C: 'violéncia' → 'violencia' (sin tilde)." },
  { f:"2022-3A", texto_previo:"Tras la", A:{word:"intervencion",error:true}, texto_AB:"del", B:{word:"rector",error:false}, texto_BC:"hubo", C:{word:"réplica",error:false}, texto_CD:"y", D:{word:"contrarréplica",error:false}, texto_post:".", explicacion:"A: 'intervencion' → 'intervención' (tilde en -ción)." },
  { f:"2022-3A", texto_previo:"Me", A:{word:"extrañó",error:false}, texto_AB:"que no", B:{word:"supiérais",error:false}, texto_BC:"que la", C:{word:"víbora",error:false}, texto_CD:"es un animal", D:{word:"carnívoro",error:false}, texto_post:".", explicacion:"Todas correctas." },
  // 2023 – 1A
  { f:"2023-1A", texto_previo:"Se", A:{word:"urgaba",error:false}, texto_AB:"en los", B:{word:"hematomas",error:false}, texto_BC:"que le", C:{word:"havía",error:true}, texto_CD:"producido la", D:{word:"heroína",error:false}, texto_post:".", explicacion:"C: 'havía' → 'había' (b)." },
  { f:"2023-1A", texto_previo:"", A:{word:"Estuvo",error:false}, texto_AB:"", B:{word:"callegeando",error:true}, texto_BC:"por", C:{word:"hangostos",error:true}, texto_CD:"", D:{word:"pasajes",error:false}, texto_post:".", explicacion:"B: 'callegeando' → 'callejeando' (j). C: 'hangostos' → 'angostos' (sin h)." },
  { f:"2023-1A", texto_previo:"Incluso los pacientes más", A:{word:"belijerantes",error:true}, texto_AB:"parecen", B:{word:"abducidos",error:false}, texto_BC:"o", C:{word:"himnotizados",error:true}, texto_CD:"por los", D:{word:"psiquiatras",error:false}, texto_post:".", explicacion:"A: 'belijerantes' → 'beligerantes' (g). C: 'himnotizados' → 'hipnotizados' (p)." },
  { f:"2023-1A", texto_previo:"Me", A:{word:"da",error:false}, texto_AB:"igual el dinero que", B:{word:"tú",error:false}, texto_BC:"le", C:{word:"des",error:false}, texto_CD:"a", D:{word:"él",error:false}, texto_post:".", explicacion:"Todas correctas." },
  { f:"2023-1A", texto_previo:"Primero le", A:{word:"extrajeron",error:false}, texto_AB:"una muela y tuvo una", B:{word:"afección",error:false}, texto_BC:"", C:{word:"bucal",error:false}, texto_CD:"Luego se le inflamaron las cuerdas", D:{word:"bocales",error:true}, texto_post:".", explicacion:"D: 'bocales' → 'vocales' (v)." },
  // 2023 – 2A
  { f:"2023-2A", texto_previo:"", A:{word:"Momentaneamente",error:true}, texto_AB:"se", B:{word:"sentía",error:false}, texto_BC:"", C:{word:"apavullado",error:true}, texto_CD:"y", D:{word:"aturdido",error:false}, texto_post:".", explicacion:"A: 'Momentaneamente' → 'Momentáneamente' (tilde). C: 'apavullado' → 'apabullado' (b)." },
  { f:"2023-2A", texto_previo:"El", A:{word:"sexagenario",error:false}, texto_AB:"", B:{word:"habitaba",error:false}, texto_BC:"en una", C:{word:"chavola",error:false}, texto_CD:"", D:{word:"inmunda",error:false}, texto_post:".", explicacion:"Todas correctas." },
  { f:"2023-2A", texto_previo:"La", A:{word:"mayoría",error:false}, texto_AB:"de los condenados", B:{word:"fuéron",error:true}, texto_BC:"", C:{word:"amnistiados",error:false}, texto_CD:"o", D:{word:"esculpados",error:true}, texto_post:".", explicacion:"B: 'fuéron' → 'fueron' (sin tilde). D: 'esculpados' → 'exculpados' (exc-)." },
  { f:"2023-2A", texto_previo:"", A:{word:"Cobijaos",error:false}, texto_AB:"en el", B:{word:"refujio",error:true}, texto_BC:", que os", C:{word:"vais",error:false}, texto_CD:"a", D:{word:"costipar",error:true}, texto_post:".", explicacion:"B: 'refujio' → 'refugio' (g). D: 'costipar' → 'constipar' (n)." },
  { f:"2023-2A", texto_previo:"Yo no me", A:{word:"habria",error:true}, texto_AB:"", B:{word:"vurlado",error:true}, texto_BC:"de los", C:{word:"indigenas",error:true}, texto_CD:"que hicieron", D:{word:"budú",error:false}, texto_post:".", explicacion:"A: 'habria' → 'habría' (tilde). B: 'vurlado' → 'burlado' (b). C: 'indigenas' → 'indígenas' (tilde)." },
  // 2024 – 1A
  { f:"2024-1A", texto_previo:"La", A:{word:"abilitación",error:true}, texto_AB:"de seguridad es una", B:{word:"condicion",error:true}, texto_BC:"", C:{word:"sine qua non",error:false}, texto_CD:"para", D:{word:"azquirir",error:true}, texto_post:"el permiso.", explicacion:"A: 'abilitación' → 'habilitación'. B: 'condicion' → 'condición'. D: 'azquirir' → 'adquirir' (d)." },
  { f:"2024-1A", texto_previo:"El", A:{word:"cozinero",error:true}, texto_AB:"", B:{word:"echó",error:false}, texto_BC:"agua", C:{word:"irviendo",error:true}, texto_CD:"a la", D:{word:"olla",error:false}, texto_post:".", explicacion:"A: 'cozinero' → 'cocinero'. C: 'irviendo' → 'hirviendo' (h y b)." },
  { f:"2024-1A", texto_previo:"El", A:{word:"olograma",error:true}, texto_AB:"representó una", B:{word:"esperiencia",error:true}, texto_BC:"", C:{word:"virtual",error:false}, texto_CD:"nunca", D:{word:"vista",error:false}, texto_post:".", explicacion:"A: 'olograma' → 'holograma' (h). B: 'esperiencia' → 'experiencia' (exp-)." },
  { f:"2024-1A", texto_previo:"El", A:{word:"estranjero",error:true}, texto_AB:"", B:{word:"anduvo",error:false}, texto_BC:"", C:{word:"duvitativo",error:true}, texto_CD:"por la", D:{word:"elección",error:false}, texto_post:"de las nuevas asignaturas.", explicacion:"A: 'estranjero' → 'extranjero' (x). C: 'duvitativo' → 'dubitativo' (b)." },
  { f:"2024-1A", texto_previo:"Las", A:{word:"hueyas",error:true}, texto_AB:"de los", B:{word:"mamiferos",error:true}, texto_BC:"eran más profundas que las de los", C:{word:"ovíparos",error:false}, texto_CD:".", D:{word:"",error:false}, texto_post:"", explicacion:"A: 'hueyas' → 'huellas' (ll). B: 'mamiferos' → 'mamíferos' (tilde)." },
  // 2024 – 2A
  { f:"2024-2A", texto_previo:"En esta", A:{word:"region",error:true}, texto_AB:"solemos", B:{word:"husar",error:true}, texto_BC:"el", C:{word:"estándar",error:false}, texto_CD:"europeo.", D:{word:"",error:false}, texto_post:"", explicacion:"A: 'region' → 'región' (tilde). B: 'husar' → 'usar' (sin h)." },
  { f:"2024-2A", texto_previo:"El", A:{word:"zócalo",error:false}, texto_AB:"de la", B:{word:"zelda",error:false}, texto_BC:"estaba roto y", C:{word:"enbarrado",error:true}, texto_CD:"de las pisadas.", D:{word:"",error:false}, texto_post:"", explicacion:"C: 'enbarrado' → 'embarrado' (mb)." },
  { f:"2024-2A", texto_previo:"El", A:{word:"ortelano",error:true}, texto_AB:"ha sembrado", B:{word:"ceboyas",error:true}, texto_BC:"y", C:{word:"zanahorias",error:false}, texto_CD:"en invierno.", D:{word:"",error:false}, texto_post:"", explicacion:"A: 'ortelano' → 'hortelano' (h). B: 'ceboyas' → 'cebollas' (ll)." },
  { f:"2024-2A", texto_previo:"El", A:{word:"asta",error:false}, texto_AB:"del animal, agudo e", B:{word:"hiriente",error:false}, texto_BC:", se", C:{word:"clavó",error:false}, texto_CD:"en el costado y se", D:{word:"desmalló",error:true}, texto_post:".", explicacion:"D: 'desmalló' → 'desmayó' (y)." },
  { f:"2024-2A", texto_previo:"Ayer el", A:{word:"autobus",error:true}, texto_AB:"", B:{word:"atropeyó",error:true}, texto_BC:"a dos peatones a las", C:{word:"seis",error:false}, texto_CD:"de la mañana.", D:{word:"",error:false}, texto_post:"", explicacion:"A: 'autobus' → 'autobús' (tilde). B: 'atropeyó' → 'atropelló' (ll)." },
  // 2024 – 3A
  { f:"2024-3A", texto_previo:"El", A:{word:"arbol",error:true}, texto_AB:"está", B:{word:"echo",error:true}, texto_BC:"de", C:{word:"hojas",error:false}, texto_CD:"", D:{word:"enrrojecidas",error:true}, texto_post:"y amarillentas.", explicacion:"A: 'arbol' → 'árbol'. B: 'echo' → 'hecho' (h). D: 'enrrojecidas' → 'enrojecidas' (una r)." },
  { f:"2024-3A", texto_previo:"El", A:{word:"viceconde",error:false}, texto_AB:"era", B:{word:"solvente",error:false}, texto_BC:"", C:{word:"economicamente",error:true}, texto_CD:"para afrontar las reclamaciones.", D:{word:"",error:false}, texto_post:"", explicacion:"C: 'economicamente' → 'económicamente' (tilde)." },
  { f:"2024-3A", texto_previo:"El barco", A:{word:"vicolor",error:true}, texto_AB:"", B:{word:"estava",error:true}, texto_BC:"atascado en la", C:{word:"playa",error:false}, texto_CD:"por una", D:{word:"averia",error:true}, texto_post:".", explicacion:"A: 'vicolor' → 'bicolor' (b). B: 'estava' → 'estaba' (b). D: 'averia' → 'avería' (tilde)." },
  { f:"2024-3A", texto_previo:"Todos", A:{word:"dedugimos",error:true}, texto_AB:"que el", B:{word:"honbre",error:true}, texto_BC:"", C:{word:"sexagenario",error:false}, texto_CD:"no le gustaba el", D:{word:"jarabe",error:false}, texto_post:".", explicacion:"A: 'dedugimos' → 'dedujimos' (j). B: 'honbre' → 'hombre' (mb)." },
  { f:"2024-3A", texto_previo:"El", A:{word:"costipado",error:false}, texto_AB:"le", B:{word:"izo",error:true}, texto_BC:"tomar muchos", C:{word:"antibióticos",error:false}, texto_CD:"pese a su", D:{word:"oposicion",error:true}, texto_post:".", explicacion:"B: 'izo' → 'hizo' (h). D: 'oposicion' → 'oposición' (tilde)." },
  // 2025 simulacros
  { f:"2025-sim", texto_previo:"El", A:{word:"cozinero",error:true}, texto_AB:"echó agua", B:{word:"irviendo",error:true}, texto_BC:"a la", C:{word:"olla",error:false}, texto_CD:".", D:{word:"",error:false}, texto_post:"", explicacion:"A: 'cozinero' → 'cocinero'. B: 'irviendo' → 'hirviendo'." },
  { f:"2025-sim", texto_previo:"Las", A:{word:"hueyas",error:true}, texto_AB:"de los", B:{word:"ovíparos",error:false}, texto_BC:"eran menos profundas que las de los", C:{word:"mamíferos",error:false}, texto_CD:".", D:{word:"",error:false}, texto_post:"", explicacion:"A: 'hueyas' → 'huellas' (ll)." },
  { f:"2025-sim", texto_previo:"Los", A:{word:"jovenes",error:true}, texto_AB:"pidieron una hamburguesa y un", B:{word:"bistec",error:false}, texto_BC:"con mucha", C:{word:"mayonesa",error:false}, texto_CD:".", D:{word:"",error:false}, texto_post:"", explicacion:"A: 'jovenes' → 'jóvenes' (tilde)." },
  { f:"2025-sim", texto_previo:"El", A:{word:"viceconde",error:false}, texto_AB:"era", B:{word:"solvente",error:false}, texto_BC:"", C:{word:"economicamente",error:true}, texto_CD:"para afrontar las", D:{word:"reclamaciones",error:false}, texto_post:".", explicacion:"C: 'economicamente' → 'económicamente' (tilde)." },
  { f:"2025-sim", texto_previo:"El", A:{word:"costipado",error:false}, texto_AB:"le", B:{word:"izo",error:true}, texto_BC:"tomar muchos", C:{word:"antibióticos",error:false}, texto_CD:"pese a su", D:{word:"oposicion",error:true}, texto_post:".", explicacion:"B: 'izo' → 'hizo' (h). D: 'oposicion' → 'oposición'." },
  { f:"2025-sim", texto_previo:"El", A:{word:"lejendario",error:true}, texto_AB:"caballero sidiano se", B:{word:"prosternó",error:false}, texto_BC:"ante la", C:{word:"magnificencia",error:false}, texto_CD:"de la reina.", D:{word:"",error:false}, texto_post:"", explicacion:"A: 'lejendario' → 'legendario' (g antes de e)." },
  { f:"2025-sim", texto_previo:"La", A:{word:"envestida",error:true}, texto_AB:"del", B:{word:"cornúpeta",error:false}, texto_BC:"", C:{word:"lició",error:true}, texto_CD:"al", D:{word:"toreador",error:false}, texto_post:".", explicacion:"A: 'envestida' → 'embestida' (mb). C: 'lició' → 'lidió' (d)." },
  { f:"2025-sim", texto_previo:"El", A:{word:"filántropo",error:false}, texto_AB:"", B:{word:"inaguró",error:true}, texto_BC:"la", C:{word:"emeroteca",error:true}, texto_CD:"durante la solemne", D:{word:"ceremonia",error:false}, texto_post:".", explicacion:"B: 'inaguró' → 'inauguró'. C: 'emeroteca' → 'hemeroteca' (h)." },
  { f:"2025-sim", texto_previo:"La", A:{word:"catarsis",error:false}, texto_AB:"teatral conmovió", B:{word:"ondamente",error:true}, texto_BC:"la", C:{word:"consciencia",error:false}, texto_CD:"", D:{word:"colectiba",error:true}, texto_post:".", explicacion:"B: 'ondamente' → 'hondamente' (h). D: 'colectiba' → 'colectiva' (v)." },
  { f:"2025-sim", texto_previo:"El", A:{word:"hayazgo",error:true}, texto_AB:"de la", B:{word:"balla",error:true}, texto_BC:"junto al", C:{word:"quiosco",error:false}, texto_CD:"fue una", D:{word:"escepción",error:true}, texto_post:".", explicacion:"A: 'hayazgo' → 'hallazgo' (ll). B: 'balla' → 'valla' (v). D: 'escepción' → 'excepción'." },
  { f:"2025-sim", texto_previo:"El gentío", A:{word:"juzgó",error:false}, texto_AB:"su", B:{word:"balía",error:true}, texto_BC:"sin", C:{word:"urgar",error:true}, texto_CD:"en aquella confusa", D:{word:"dedución",error:true}, texto_post:".", explicacion:"B: 'balía' → 'valía' (v). C: 'urgar' → 'hurgar' (h). D: 'dedución' → 'deducción' (cc)." },
  { f:"2025-sim", texto_previo:"El", A:{word:"rocín",error:false}, texto_AB:"relinchó bajo la", B:{word:"mollina",error:false}, texto_BC:"que", C:{word:"hanegaba",error:true}, texto_CD:"el", D:{word:"hocino",error:false}, texto_post:".", explicacion:"C: 'hanegaba' → 'anegaba' (sin h)." },
  { f:"2025-sim", texto_previo:"La", A:{word:"heroína",error:false}, texto_AB:"llevaba una", B:{word:"girafa",error:true}, texto_BC:"de", C:{word:"ferpa",error:true}, texto_CD:"con detalles", D:{word:"insólitos",error:false}, texto_post:".", explicacion:"B: 'girafa' → 'jirafa' (j). C: 'ferpa' → 'felpa' (l)." },
  { f:"2025-sim", texto_previo:"El tiempo de la", A:{word:"miés",error:true}, texto_AB:"era", B:{word:"irreemplazable",error:false}, texto_BC:"para los", C:{word:"jíbaros",error:false}, texto_CD:"de la", D:{word:"hacienda",error:false}, texto_post:".", explicacion:"A: 'miés' → 'mies' (llana en s, sin tilde)." },
];

// ══════════════════════════════════════════════════════════════════════
// BANCO GRAMÁTICA — Preguntas reales de exámenes oficiales
// ══════════════════════════════════════════════════════════════════════
const TODAS_PREGUNTAS_GRAM = [
  // 2022
  { f:"2022-1A", A:"Me se olvidó comprar huevos.", B:"A Juan se le cayeron las uvas al suelo.", C:"Eso está prohibido. Haz se lo saber, por favor.", D:"Ayer se os dijo que vinieseis hoy.", incorrectas:["A","C"], principal:"A", explicacion:"A: 'Me se' → 'Se me' (orden de pronombres). C: 'Haz se lo' → 'Házselo' (pronombres se unen al imperativo)." },
  { f:"2022-1A", A:"Acercaros que os diga algo.", B:"Tened cuidado con el perro.", C:"Tenéis que veniros conmigo.", D:"Vosotros id arriba y yo me quedo abajo.", incorrectas:["A"], principal:"A", explicacion:"A: 'Acercaros' → 'Acercaos' (imperativo 2ª pl.: pierde la -r antes de -os)." },
  { f:"2022-1A", A:"A ver si llegan mañana o más tarde.", B:"Tenían que haber llegado ya.", C:"Hubieron muchas personas en el acto de ayer.", D:"Aquello teníamos que haberlo previsto antes.", incorrectas:["C"], principal:"C", explicacion:"C: 'Hubieron' → 'Hubo' (haber impersonal: siempre singular)." },
  { f:"2022-1A", A:"¿Porqué has llegado tarde?", B:"Voy hacer la comida.", C:"Juan y Irene viven en Madrid.", D:"Necesito saber el porqué.", incorrectas:["A","B"], principal:"A", explicacion:"A: '¿Porqué?' → '¿Por qué?' (dos palabras en interrogativas). B: 'Voy hacer' → 'Voy a hacer' (ir a + infinitivo)." },
  { f:"2022-1A", A:"Me alegro de que estés bien.", B:"Pensé que vendrías antes.", C:"Anoche llegastes muy tarde.", D:"Ayer anduvimos diez kilómetros.", incorrectas:["C"], principal:"C", explicacion:"C: 'llegastes' → 'llegaste' (el pretérito indefinido de 2ª pers. no lleva -s)." },
  { f:"2022-2A", A:"No quiso que nos acercáramos.", B:"Ayer conducimos durante diez horas.", C:"Eso habría que haberlo hecho antes.", D:"Si no se habría acercado tanto, no se hubiera caído.", incorrectas:["D"], principal:"D", explicacion:"D: 'Si no se habría acercado' → 'Si no se hubiera acercado' (condicional incorrecto en la prótasis)." },
  { f:"2022-2A", A:"No me gusta de que hagas eso.", B:"Ayer supe que llegabas hoy.", C:"Soy consciente de que es un crío.", D:"Me preguntaba de qué trataba esa película.", incorrectas:["A"], principal:"A", explicacion:"A: dequeísmo. 'No me gusta de que' → 'No me gusta que'." },
  { f:"2022-2A", A:"Tomaos el refresco ya.", B:"Hay mucho humo entorno a la nave.", C:"Desdeque tuve el bebé no he pegado ojo.", D:"Tenéis que marcharos ya.", incorrectas:["B","C"], principal:"B", explicacion:"B: 'entorno' → 'en torno' (dos palabras cuando es prep. + sust.). C: 'Desdeque' → 'Desde que'." },
  { f:"2022-2A", A:"No previeron lo que iba a pasar.", B:"Yo no he pedido nada, asique no me interesa.", C:"Ayer traímos el dinero necesario.", D:"No sé la persona a la que dirigirme.", incorrectas:["B"], principal:"B", explicacion:"B: 'asique' → 'así que' (dos palabras)." },
  { f:"2022-2A", A:"Juan a venido solo.", B:"El agua está muy sucia.", C:"¿Cuándo llega Juan?", D:"No sé de qué te quejas.", incorrectas:["A"], principal:"A", explicacion:"A: 'a venido' → 'ha venido' (h en el auxiliar haber)." },
  { f:"2022-3A", A:"Me conformo conque lleguéis a vuestra hora.", B:"Se prevé que hayan muchas lluvias.", C:"Antes de que salga el sol habremos llegado.", D:"Dejaste el arma cargado.", incorrectas:["D"], principal:"D", explicacion:"D: 'el arma cargado' → 'el arma cargada' (femenino aunque lleva el)." },
  { f:"2022-3A", A:"Mañana cuándo llegues, me avisas.", B:"Prefiero que sean ellos quienes lo hagan.", C:"Tú eres de los que consideras que debo dimitir.", D:"Hay que coger el toro por los cuernos.", incorrectas:["A"], principal:"A", explicacion:"A: 'cuándo' con tilde solo en interrogativas/exclamativas. Aquí es conjunción temporal: 'cuando' (sin tilde)." },
  { f:"2022-3A", A:"El detenido se autolesionó, es decir, se provocó las lesiones a sí mismo.", B:"Irene es la mujer de la que te hablé.", C:"Vosotros, si queréis, venirse conmigo.", D:"A ti se te olvidó ayer de comprar el pan.", incorrectas:["C","D"], principal:"C", explicacion:"C: 'venirse' → 'venios'. D: queísmo inverso: 'olvidó de comprar' → 'olvidó comprar'." },
  { f:"2022-3A", A:"El jefe dispuso que se hiciera cuanto antes.", B:"Según la normativa, dispones de dos días para la reclamación.", C:"¿Qué ciudad te gusta más: Gijón o Oviedo?", D:"¿Donde has dejado el paraguas?", incorrectas:["D"], principal:"D", explicacion:"D: '¿Donde?' → '¿Dónde?' (interrogativo lleva tilde)." },
  { f:"2022-3A", A:"Hazlo sólo en caso de que sea necesario.", B:"Contra más trabajes más te pagarán.", C:"Soy tan alto que no quepo en el coche.", D:"Animémoslo a que siga.", incorrectas:["A","B"], principal:"B", explicacion:"A: 'sólo' ya no lleva tilde (RAE 2010). B: 'Contra más' → 'Cuanto más'." },
  // 2023
  { f:"2023-1A", A:"Ana no cree que la entiendan.", B:"Está en el piso doceavo.", C:"El detenido es adicto de la cocaína.", D:"La orca macho es muy peligroso.", incorrectas:["B","C","D"], principal:"B", explicacion:"B: 'doceavo' es fraccionario, no ordinal ('duodécimo'). C: 'adicto de' → 'adicto a'. D: 'La orca macho ... peligrosa'." },
  { f:"2023-1A", A:"No ha aparecido el arma con la que cometió el crimen.", B:"Siguió luchando aun cuando lo tenía todo perdido.", C:"Se enfadó con sigo mismo.", D:"Lo miró de arriba abajo.", incorrectas:["C"], principal:"C", explicacion:"C: 'con sigo' → 'consigo' (pronombre reflexivo, se escribe junto)." },
  { f:"2023-1A", A:"Juan llegó muy tarde. Sin encambio, Ana estaba aquí a las diez.", B:"Voy a el supermercado.", C:"Los hechos ocurrieron en aquella época.", D:"Cógete de mi brazo.", incorrectas:["A","B"], principal:"A", explicacion:"A: 'Sin encambio' → 'Sin embargo'. B: 'a el' → 'al' (contracción obligatoria)." },
  { f:"2023-1A", A:"Su actuación se considera cuasidelito.", B:"Aún me queda dinero.", C:"Ahora mismo estoy muy agusto.", D:"Yo soy de los que apoyo siempre al débil.", incorrectas:["C","D"], principal:"C", explicacion:"C: 'agusto' → 'a gusto' (dos palabras). D: 'apoyo' → 'apoyan' (concordancia con 'los que')." },
  { f:"2023-1A", A:"Anoche me estaba divirtiendo mucho justo antes de irme.", B:"¿Cuantas horas trabajas al día?", C:"Abrázame fuerte.", D:"Comió mucho, tánto que se puso malo.", incorrectas:["B","D"], principal:"B", explicacion:"B: '¿Cuantas?' → '¿Cuántas?' D: 'tánto' → 'tanto' (no lleva tilde)." },
  { f:"2023-2A", A:"Quedaron décimosterceros.", B:"Lo hizo sin que su jefa tenía conocimiento de ello.", C:"De haberlo sabido antes te lo habría dicho.", D:"Llegué muy tarde, asíque me fui.", incorrectas:["A","B","D"], principal:"B", explicacion:"A: 'décimosterceros' → 'decimoterceros'. B: 'tenía' → 'tuviera' (subjuntivo tras 'sin que'). D: 'asíque' → 'así que'." },
  { f:"2023-2A", A:"Basta conque lo traigas antes de las diez.", B:"Viene de la ciudad de El Escorial.", C:"Juan sabe quién lo ha hecho.", D:"El coche circulaba cuestarriba.", incorrectas:["D"], principal:"D", explicacion:"D: 'cuestarriba' → 'cuesta arriba' (dos palabras)." },
  { f:"2023-2A", A:"La elefante hembra es muy grande.", B:"Déjame en paz.", C:"Se buscan a los culpables.", D:"Se me olvidó en muchas ocasiones.", incorrectas:["A","C"], principal:"A", explicacion:"A: 'La elefante' → 'La elefanta'. C: 'Se buscan a' → 'Se busca a' (impersonal con 'a' no concuerda)." },
  { f:"2023-2A", A:"Te daré mil euros acambio de tu silencio.", B:"Ese líquido es semi transparente.", C:"¿A tí te gusta el vino?", D:"La víctima no se atrevía si quiera a recordar.", incorrectas:["A","C","D"], principal:"C", explicacion:"A: 'acambio' → 'a cambio'. C: '¿A tí?' → '¿A ti?' (sin tilde). D: 'si quiera' → 'siquiera'." },
  { f:"2023-2A", A:"Dí me lo que tengo que hacer.", B:"Cuantimás dinero tengas más feliz serás.", C:"Los espectadores contuvieron sus lágrimas.", D:"No me iré sin que tú me des permiso.", incorrectas:["A","B"], principal:"B", explicacion:"A: 'Dí me' → 'Dime'. B: 'Cuantimás' → 'Cuanto más' (dos palabras)." },
  // 2024
  { f:"2024-1A", A:"Seguiré adelante con la condición que tú también lo hagas.", B:"Los contrincantes se golpeaban entresí.", C:"El objeto se localizó en esta área concreta.", D:"La primera y la segunda son buenas soluciones.", incorrectas:["A","B"], principal:"A", explicacion:"A: queísmo: 'con la condición que' → 'con la condición de que'. B: 'entresí' → 'entre sí'." },
  { f:"2024-1A", A:"Habría que tener en cuenta muchas cosas.", B:"Busqué las llaves donde siempre las dejo.", C:"No creo que vengan hoy.", D:"Los profesores ponieron el examen encima de la mesa.", incorrectas:["D"], principal:"D", explicacion:"D: 'ponieron' → 'pusieron' (pretérito irregular de poner)." },
  { f:"2024-1A", A:"Tengo la certeza de que vendrá.", B:"Vamos haber si llega a tiempo.", C:"No sabemos qué hacer.", D:"Cerca de la mitad de los trabajadores eran inmigrantes.", incorrectas:["B"], principal:"B", explicacion:"B: 'Vamos haber' → 'Vamos a ver' (haber/ver confusión + falta prep. a)." },
  { f:"2024-1A", A:"Estaba acercándose mucho, cuando se precipitó al vacío.", B:"Esa novela es muy de su gusto.", C:"Si tenéis frío, cerraríamos la ventana.", D:"Coger eso del suelo, por favor.", incorrectas:["C","D"], principal:"C", explicacion:"C: 'cerraríamos' → 'cerrad' (condicional incorrecto). D: infinitivo por imperativo: 'Coged'." },
  { f:"2024-1A", A:"Cuando mejor estábamos, nos tuvimos que ir.", B:"Está previsto que hayan muchas lluvias.", C:"Le compré un ramo de flores a mi hija.", D:"Me obligaron a hacerlo.", incorrectas:["A","B"], principal:"A", explicacion:"A: 'Cuando mejor' → sin corrección clara; es expresión incorrecta. B: 'hayan' → 'haya' (haber impersonal)." },
  { f:"2024-2A", A:"Quedo a la espera que me concretes el horario.", B:"Los jugadores y el árbitro saltó juntos al campo.", C:"En ese local se hacen arreglos de ropa.", D:"Cuanta más gente venga, mejor.", incorrectas:["A","B"], principal:"A", explicacion:"A: queísmo: 'a la espera que' → 'a la espera de que'. B: 'saltó' → 'saltaron' (concordancia)." },
  { f:"2024-2A", A:"Se estaban divirtiendo mucho.", B:"Hay dos personas asesinadas. Se tratan de dos mujeres.", C:"Que baje quien quiera.", D:"Eso se lo tengo que decir a Ana.", incorrectas:["B"], principal:"B", explicacion:"B: 'se tratan' → 'se trata' (construcción impersonal)." },
  { f:"2024-2A", A:"Aún tienes el arma cargado.", B:"Tú no te lo mereces.", C:"Todos los padres quieren que sus hijos tienen suerte.", D:"Los meteorólogos predijeron mal tiempo.", incorrectas:["A","C"], principal:"A", explicacion:"A: 'arma cargado' → 'arma cargada' (femenino). C: 'tienen' → 'tengan' (subjuntivo tras querer que)." },
  { f:"2024-2A", A:"Llegará antes de que anochezca.", B:"El coche llevo mucho tiempo sin usarle.", C:"Quejándote siempre no conseguirás nada.", D:"Tenemos que poner ese cuadro más abajo.", incorrectas:["B"], principal:"B", explicacion:"B: leísmo: 'sin usarle' → 'sin usarlo' (C.D. de cosa)." },
  { f:"2024-2A", A:"La primera opción es la más mejor.", B:"Nos han explicado muy bien cómo llegar.", C:"La mayor parte de la gente irá el domingo.", D:"Los detenidos conducieron bajo los efectos del alcohol.", incorrectas:["A"], principal:"A", explicacion:"A: 'más mejor' es un pleonasmo: 'mejor' ya es comparativo." },
  { f:"2024-3A", A:"La abad del convento salió para recibirnos.", B:"El ordenador no tiene actualizado el antivirus.", C:"Este señor es el alcalde del municipio.", D:"El mes de mayo no tiene treinta días.", incorrectas:["A"], principal:"A", explicacion:"A: 'La abad' → 'La abadesa'." },
  { f:"2024-3A", A:"El sueldo es de mil quinientos euros, más pagas.", B:"La escuadrilla está compuesta de cinco aeronaves.", C:"El primer y segundo cuarto del partido fue más intenso.", D:"¡Mira que eres despistado!", incorrectas:["C"], principal:"C", explicacion:"C: 'El primer y segundo cuarto' → 'El primer y el segundo cuarto' (cada ordinal necesita artículo)." },
  { f:"2024-3A", A:"Anoche lleguemos muy tarde.", B:"Tenéis que entreteneros con algo.", C:"Dime cuanto te debo.", D:"Entre el público había, sobre todo, muchos jóvenes.", incorrectas:["A","C"], principal:"A", explicacion:"A: 'lleguemos' → 'llegamos' (pretérito, no subjuntivo). C: 'cuanto' → 'cuánto' (interrogativa indirecta)." },
  { f:"2024-3A", A:"Esta casa no es como aquellas otras.", B:"A tu hija tienes que darla más dinero.", C:"Coged vuestras cosas y venid conmigo.", D:"Me trata como si no me conociera.", incorrectas:["B"], principal:"B", explicacion:"B: laísmo. 'darla' → 'darle' (C.I.)." },
  // 2025 simulacros
  { f:"2025-sim", A:"Intenté de que vinieras antes.", B:"No sé dónde está el bolígrafo.", C:"El haberlo hecho así es un problema.", D:"Ayer comistes arroz.", incorrectas:["A","D"], principal:"A", explicacion:"A: dequeísmo. D: 'comistes' → 'comiste'." },
  { f:"2025-sim", A:"Se estaban divirtiendo mucho.", B:"Hay dos personas asesinadas. Se tratan de dos mujeres.", C:"Que baje quien quiera.", D:"Eso se lo tengo que decir a Ana.", incorrectas:["B"], principal:"B", explicacion:"B: 'se tratan' → 'se trata' (impersonal)." },
  { f:"2025-sim", A:"Llegará antes de que anochezca.", B:"El coche llevo mucho tiempo sin usarle.", C:"Quejándote siempre no conseguirás nada.", D:"Tenemos que poner ese cuadro más abajo.", incorrectas:["B"], principal:"B", explicacion:"B: leísmo ('sin usarle' → 'sin usarlo')." },
  { f:"2025-sim", A:"La primera opción es la más mejor.", B:"Nos han explicado muy bien cómo llegar.", C:"La mayor parte de la gente irá el domingo.", D:"Los detenidos conducieron bajo los efectos del alcohol.", incorrectas:["A"], principal:"A", explicacion:"A: pleonasmo: 'más mejor' → 'mejor'." },
  { f:"2025-sim", A:"En esa familia se ayudan los unos a los otros.", B:"Habemos algunos en el grupo que no queremos cambios.", C:"Se buscan a los culpables.", D:"¿A dónde has puesto mi cartera?", incorrectas:["B"], principal:"B", explicacion:"B: 'Habemos' → 'Hay' (haber impersonal)." },
  { f:"2025-sim", A:"Las dos opciones son iguales de difíciles.", B:"El resto de los profesores irán a la huelga.", C:"Los afectados andaron varios kilómetros para llegar.", D:"Se dio cuenta que todo lo que había hecho estaba mal.", incorrectas:["A","D"], principal:"A", explicacion:"A: 'iguales de difíciles' → 'igual de difíciles'. D: queísmo ('se dio cuenta que' → 'se dio cuenta de que')." },
  { f:"2025-sim", A:"Aun siendo malos datos, hay esperanza de mejora.", B:"A tus hijos hace un año que no les veo.", C:"Si llovería, no iría.", D:"Hay que ver qué cosas tiene esa Manuela.", incorrectas:["C"], principal:"C", explicacion:"C: 'Si llovería' → 'Si lloviera' (subjuntivo en prótasis condicional)." },
  { f:"2025-sim", A:"¡Que alguien me ayude!", B:"Sentaros donde podáis.", C:"Váyase a su casa, por favor.", D:"Abajo de la repisa guarda sus llaves.", incorrectas:["D"], principal:"D", explicacion:"D: 'Abajo de' → 'Debajo de la repisa'." },
  { f:"2025-sim", A:"La alcalde ordenó lo que tenían que hacer.", B:"El trece % de los encuestados opinaba lo contrario.", C:"Debes de dejar que te ayude.", D:"Te agradezco tu ayuda, pero prefiero terminar.", incorrectas:["C"], principal:"C", explicacion:"C: 'Debes de' (probabilidad) → 'Debes dejar' (obligación)." },
  { f:"2025-sim", A:"Se acordó en que debía entregar la documentación.", B:"El médico nos recetó el mismo tratamiento a los dos.", C:"No hace falta que vengas si no quieres.", D:"Todos los agentes cumplieron su deber.", incorrectas:["A"], principal:"A", explicacion:"A: dequeísmo: 'se acordó en que' → 'se acordó de que'." },
  { f:"2025-sim", A:"El público aplaudieron con entusiasmo.", B:"La mayoría de los alumnos aprobaron.", C:"Los datos que nos diste eran incorrectos.", D:"El agente realizó su patrulla habitual.", incorrectas:["A"], principal:"A", explicacion:"A: 'El público aplaudieron' → 'El público aplaudió' (sujeto singular)." },
  { f:"2025-sim", A:"Se acerca días difíciles llenos de retos.", B:"La situación mejora poco a poco.", C:"El informe fue entregado a tiempo.", D:"Los agentes actuaron con profesionalidad.", incorrectas:["A"], principal:"A", explicacion:"A: 'Se acerca días' → 'Se acercan días' (concordancia)." },
  { f:"2025-sim", A:"Varios trabajadores decidieron abandonar de motu propio.", B:"El sargento dio las instrucciones pertinentes.", C:"La declaración fue tomada en tiempo y forma.", D:"Ninguno de los testigos recordaba el incidente.", incorrectas:["A"], principal:"A", explicacion:"A: 'motu propio' → 'motu proprio' (locución latina; no se hispaniza)." },
];

// ══════════════════════════════════════════════════════════════════════
// BANCO INGLÉS — Preguntas reales de convocatorias oficiales
// ══════════════════════════════════════════════════════════════════════
const TODAS_PREGUNTAS_ING = [
  // 2022 – Modelo A (página 18)
  { f:"2022-A", pregunta:"Lucy and Mark _____ a new life in Amsterdam.", A:"are going start", B:"are going to start", C:"going to start", D:"is going to starting", correcta:"B", explicacion:"'Going to' expresses future plans: am/is/are + going to + infinitive." },
  { f:"2022-A", pregunta:"The kids _____ their way in the town, they _____ in the countryside.", A:"don't lost / got lost", B:"didn't lose / got lose", C:"didn't lost / get lost", D:"didn't lose / got lost", correcta:"D", explicacion:"Past simple negative: didn't + bare infinitive. 'Got lost' = became lost." },
  { f:"2022-A", pregunta:"_____ country from Spain is New Zealand.", A:"The furthest", B:"The furtherest", C:"The farest", D:"The most farther", correcta:"A", explicacion:"'Far' has two superlatives: 'furthest' (distance) and 'farthest'. 'Furthest' is the most common." },
  { f:"2022-A", pregunta:"Albert _____ a better job if he _____ a degree.", A:"had find / had", B:"would find / would have", C:"would find / had", D:"would found / had have", correcta:"C", explicacion:"Third conditional: would + bare inf. / if + had + p.p." },
  { f:"2022-A", pregunta:"Has she _____?", A:"begin her new job yet", B:"already begin her new job", C:"began her new job already", D:"begun her new job yet", correcta:"D", explicacion:"Present perfect: have/has + past participle. 'Yet' in questions/negatives at the end." },
  { f:"2022-A", pregunta:"I've found the screw _____ you were looking for.", A:"whose", B:"what", C:"--", D:"who's", correcta:"C", explicacion:"'Screw' is a thing; relative pronoun can be omitted (contact clause) when it's object." },
  { f:"2022-A", pregunta:"_____ sofa is comfortable but _____ armchairs aren't.", A:"This / those", B:"These / those", C:"That / that", D:"This / that", correcta:"A", explicacion:"'Sofa' is singular → 'this'. 'Armchairs' is plural → 'those'." },
  { f:"2022-A", pregunta:"_____ any survivors?", A:"Could there being", B:"Could there been", C:"Could there be", D:"Could there to be", correcta:"C", explicacion:"'Could there be' = modal + there + bare infinitive." },
  { f:"2022-A", pregunta:"Rewrite in reported speech: Alice told me: 'I'm working on it now'.", A:"Alice told to me she has working on it now.", B:"Alice told me she was working on it then.", C:"Alice told me she working on it then.", D:"Alice told me was working on it now.", correcta:"B", explicacion:"Reported speech: present continuous → past continuous. 'Now' → 'then'." },
  { f:"2022-A", pregunta:"_____ people who cannot pay the mortgage.", A:"There are too many", B:"There are too much", C:"There is a little", D:"There are a lot", correcta:"A", explicacion:"'People' is plural → 'there are'. 'Too many' for countable nouns." },
  { f:"2022-A", pregunta:"There's a poster _____ the wall, _____ the desk.", A:"on / opposite of", B:"on / between", C:"in / above of", D:"on / above", correcta:"D", explicacion:"'On the wall' (attached to). 'Above the desk' (higher than, not touching)." },
  { f:"2022-A", pregunta:"Your nephew kept the bicycle, _____?", A:"didn't she", B:"doesn't he", C:"didn't he", D:"did she", correcta:"C", explicacion:"'Kept' is past simple → tag: 'didn't he'. Subject matches 'nephew' (he)." },
  { f:"2022-A", pregunta:"I _____ him if he _____ the truth.", A:"would have forgave / had told", B:"would have forgiven / had told me", C:"would forgiven / had tell me", D:"would have forgive / had told to me", correcta:"B", explicacion:"Third conditional: would + have + p.p. / if + had + p.p." },
  { f:"2022-A", pregunta:"Who _____ when I _____ you yesterday?", A:"were you talking to / saw", B:"you talking to / saw", C:"was you talking to / was seeing", D:"were talking to / seen", correcta:"A", explicacion:"Past continuous interrupted by past simple: 'were you talking to' / 'saw'." },
  { f:"2022-A", pregunta:"The lecture was cancelled _____ budgetary restrictions.", A:"owing for", B:"due for", C:"due to", D:"because", correcta:"C", explicacion:"'Due to' = because of (followed by noun/gerund)." },
  { f:"2022-A", pregunta:"Let me give you _____ advice: get _____ good lawyer.", A:"some / a", B:"an / a", C:"a piece / --", D:"some / an", correcta:"A", explicacion:"'Advice' is uncountable → 'some'. 'A lawyer' (consonant sound → a)." },
  { f:"2022-A", pregunta:"_____ my teeth every day when I was a child.", A:"I didn't use to brush", B:"I didn't used brush", C:"I don't use to brush", D:"I not used to brush", correcta:"A", explicacion:"'Used to' for past habits (negative: didn't use to + infinitive)." },
  { f:"2022-A", pregunta:"_____ cope with so much stress?", A:"Will he can", B:"Will he be able to", C:"Will he be able", D:"Will he able to", correcta:"B", explicacion:"Future of 'can': will be able to. 'Can' cannot follow another modal." },
  { f:"2022-A", pregunta:"This is _____ responsibility, not _____.", A:"her / our", B:"hers / us", C:"her / ours", D:"them / ours", correcta:"C", explicacion:"'Her responsibility' (adj. possessive + noun). 'Not ours' (pronoun possessive standalone)." },
  { f:"2022-A", pregunta:"-Who _____ the match last night? -I don't know, I _____ asleep.", A:"win / fell", B:"was win / fall", C:"won / fallen", D:"won / fell", correcta:"D", explicacion:"Past simple: 'won' and 'fell' (irregular past of fall)." },
  // 2022 – Modelo B (página 18)
  { f:"2022-B", pregunta:"Let me give you _____ advice: get _____ good lawyer.", A:"some / a", B:"an / a", C:"a piece / --", D:"some / an", correcta:"A", explicacion:"'Advice' uncountable → 'some'. 'A lawyer' (consonant sound → a)." },
  { f:"2022-B", pregunta:"I've found the screw _____ you were looking for.", A:"whose", B:"what", C:"--", D:"who's", correcta:"C", explicacion:"Relative pronoun omitted (contact clause) when it is the object." },
  { f:"2022-B", pregunta:"Your nephew kept the bicycle, _____?", A:"didn't she", B:"doesn't he", C:"didn't he", D:"did she", correcta:"C", explicacion:"Past simple → tag: 'didn't he'. Matches 'nephew' (he)." },
  { f:"2022-B", pregunta:"This is _____ responsibility, not _____.", A:"her / our", B:"hers / us", C:"her / ours", D:"them / ours", correcta:"C", explicacion:"'Her' (adj. possessive + noun). 'Ours' (standalone possessive pronoun)." },
  { f:"2022-B", pregunta:"Rewrite in reported speech: Alice told me: 'I'm working on it now'.", A:"Alice told to me she has working on it now.", B:"Alice told me she was working on it then.", C:"Alice told me she working on it then.", D:"Alice told me was working on it now.", correcta:"B", explicacion:"Present continuous → past continuous in reported speech. 'Now' → 'then'." },
  { f:"2022-B", pregunta:"The lecture was cancelled _____ budgetary restrictions.", A:"owing for", B:"due for", C:"due to", D:"because", correcta:"C", explicacion:"'Due to' = because of (followed by noun phrase)." },
  { f:"2022-B", pregunta:"The kids _____ their way in the town, they _____ in the countryside.", A:"don't lost / got lost", B:"didn't lose / got lose", C:"didn't lost / get lost", D:"didn't lose / got lost", correcta:"D", explicacion:"Past simple negative: didn't + bare infinitive. 'Got lost' = became lost." },
  { f:"2022-B", pregunta:"_____ my teeth every day when I was a child.", A:"I didn't use to brush", B:"I didn't used brush", C:"I don't use to brush", D:"I not used to brush", correcta:"A", explicacion:"'Used to' negative: didn't use to + bare infinitive." },
  { f:"2022-B", pregunta:"Has she _____?", A:"begin her new job yet", B:"already begin her new job", C:"began her new job already", D:"begun her new job yet", correcta:"D", explicacion:"Present perfect: have + p.p. 'Yet' in questions at the end." },
  { f:"2022-B", pregunta:"-Who _____ the match last night? -I don't know, I _____ asleep.", A:"win / fell", B:"was win / fall", C:"won / fallen", D:"won / fell", correcta:"D", explicacion:"Past simple: 'won' (irregular) and 'fell' (irregular past of fall)." },
  { f:"2022-B", pregunta:"_____ sofa is comfortable but _____ armchairs aren't.", A:"This / those", B:"These / those", C:"That / that", D:"This / that", correcta:"A", explicacion:"'Sofa' singular → 'this'. 'Armchairs' plural → 'those'." },
  { f:"2022-B", pregunta:"_____ country from Spain is New Zealand.", A:"The furthest", B:"The furtherest", C:"The farest", D:"The most farther", correcta:"A", explicacion:"'Furthest' is the superlative of far for abstract/metaphorical distance." },
  { f:"2022-B", pregunta:"_____ people who cannot pay the mortgage.", A:"There are too many", B:"There are too much", C:"There is a little", D:"There are a lot", correcta:"A", explicacion:"'People' plural → 'there are'. 'Too many' for countable nouns." },
  { f:"2022-B", pregunta:"Lucy and Mark _____ a new life in Amsterdam.", A:"are going start", B:"are going to start", C:"going to start", D:"is going to starting", correcta:"B", explicacion:"'Going to' plans: am/is/are + going to + bare infinitive." },
  { f:"2022-B", pregunta:"There's a poster _____ the wall, _____ the desk.", A:"on / opposite of", B:"on / between", C:"in / above of", D:"on / above", correcta:"D", explicacion:"'On the wall' (surface). 'Above the desk' (higher position)." },
  { f:"2022-B", pregunta:"_____ cope with so much stress?", A:"Will he can", B:"Will he be able to", C:"Will he be able", D:"Will he able to", correcta:"B", explicacion:"Future of 'can': will be able to + bare infinitive." },
  { f:"2022-B", pregunta:"Who _____ when I _____ you yesterday?", A:"were you talking to / saw", B:"you talking to / saw", C:"was you talking to / was seeing", D:"were talking to / seen", correcta:"A", explicacion:"Past continuous interrupted by past simple." },
  { f:"2022-B", pregunta:"Albert _____ a better job if he _____ a degree.", A:"had find / had", B:"would find / would have", C:"would find / had", D:"would found / had have", correcta:"C", explicacion:"Third conditional: would + bare inf. / if + had + p.p." },
  { f:"2022-B", pregunta:"_____ any survivors?", A:"Could there being", B:"Could there been", C:"Could there be", D:"Could there to be", correcta:"C", explicacion:"'Could there be' = modal + bare infinitive." },
  { f:"2022-B", pregunta:"I _____ him if he _____ the truth.", A:"would have forgave / had told", B:"would have forgiven / had told me", C:"would forgiven / had tell me", D:"would have forgive / had told to me", correcta:"B", explicacion:"Third conditional: would + have + p.p. / if + had + p.p." },
  // 2023 – Modelo A (página 18)
  { f:"2023-A", pregunta:"When did you become a policewoman?", A:"From 5 years ago.", B:"Since 5 years ago.", C:"5 years ago.", D:"For 5 years ago.", correcta:"C", explicacion:"'When' asks for a specific point in time → simple past answer: '5 years ago'." },
  { f:"2023-A", pregunta:"The book _____ I read last week was awesome!", A:"--", B:"who", C:"what", D:"whose", correcta:"A", explicacion:"Relative pronoun omitted when it is the object (contact clause)." },
  { f:"2023-A", pregunta:"-_____ do you drink on a daily basis? -_____.", A:"How many water / A lots", B:"How much water / A lot", C:"How many waters / A lot", D:"How much water / Lot", correcta:"B", explicacion:"'Water' is uncountable → 'How much'. 'A lot' (standalone, no 'of')." },
  { f:"2023-A", pregunta:"_____ several changes in the company.", A:"There have be", B:"There are been", C:"There have being", D:"There have been", correcta:"D", explicacion:"Present perfect: there + have + been." },
  { f:"2023-A", pregunta:"Thomas is _____ he used to be.", A:"healthier that", B:"healthier than", C:"healthiest than", D:"more health than", correcta:"B", explicacion:"Comparative + than: 'healthier than'." },
  { f:"2023-A", pregunta:"_____ a priest?", A:"How long have you been", B:"How long are you been", C:"How long have you being", D:"How many time have you been", correcta:"A", explicacion:"'How long have you been...?' = present perfect for duration." },
  { f:"2023-A", pregunta:"-How often _____ exercise? -_____.", A:"does Helen take / Once at week", B:"does take Helen / Once week", C:"has Helen take / One a week", D:"does Helen take / Twice a week", correcta:"D", explicacion:"Present simple for routines. 'Twice a week' is a valid frequency expression." },
  { f:"2023-A", pregunta:"-Hey, look at that cave! -Wow! _____.", A:"How a beautiful!", B:"How beautiful!", C:"What beautiful!", D:"What a beautiful!", correcta:"B", explicacion:"'How + adjective' in exclamations without a noun. 'What + (a) + adj + noun'." },
  { f:"2023-A", pregunta:"If we _____ the lottery results in advance, we _____ rich!", A:"had know / would all be", B:"knew / would all been", C:"knew / would all be", D:"would known / had all be", correcta:"C", explicacion:"Second conditional: if + past simple / would + bare infinitive." },
  { f:"2023-A", pregunta:"She can speak 4 languages, _____?", A:"can't she", B:"doesn't she", C:"can't her", D:"does she", correcta:"A", explicacion:"Tag question: affirmative → negative tag. 'Can' → 'can't she'." },
  { f:"2023-A", pregunta:"The law firm is _____ the 7th floor, _____ the jewellery.", A:"on / near of", B:"in / near", C:"on / next to", D:"on / next of", correcta:"B", explicacion:"'On the 7th floor'. 'Near the jewellery' (near: no 'of')." },
  { f:"2023-A", pregunta:"I found two _____ dollars.", A:"hundred of", B:"hundreds of", C:"thousand of", D:"hundred", correcta:"D", explicacion:"After numbers, 'hundred' has no -s and no 'of': 'two hundred dollars'." },
  { f:"2023-A", pregunta:"Frank _____ by a poisonous snake last week.", A:"would bitten", B:"was bitten", C:"was bit", D:"was bited", correcta:"B", explicacion:"Passive: was/were + past participle. Past p.p. of 'bite' = 'bitten'." },
  { f:"2023-A", pregunta:"'Did you bring your waterproof jackets?' She asked them _____ waterproof jackets.", A:"whether they had bringed their", B:"if they bought their", C:"if they have brought my", D:"if they had brought their", correcta:"D", explicacion:"Reported question: had + p.p. (past perfect). 'Your' → 'their'." },
  { f:"2023-A", pregunta:"_____, she had fastened her seat belt.", A:"Luckingly", B:"Luckly", C:"Luckedly", D:"Luckily", correcta:"D", explicacion:"Adverb from 'lucky': luckily (y → ily)." },
  { f:"2023-A", pregunta:"The police officer _____ open the boot.", A:"told me to", B:"tell me to", C:"told to me", D:"said me to", correcta:"A", explicacion:"tell/ask + object + to + infinitive: 'told me to open'." },
  { f:"2023-A", pregunta:"Mr Smith _____ our company last year.", A:"refused join", B:"refused to join", C:"denied join", D:"denied to joining", correcta:"B", explicacion:"'Refuse' is followed by to + infinitive." },
  { f:"2023-A", pregunta:"Do you know _____?", A:"where are my glass", B:"where is my glasses", C:"where my glasses are", D:"where my glasses is", correcta:"C", explicacion:"Indirect question: statement word order (where + subject + verb)." },
  { f:"2023-A", pregunta:"I'm _____ but John and Louis are _____.", A:"a waiter / cooks", B:"a waiter / a cooks", C:"waiter / cook", D:"a waiters / cooks", correcta:"A", explicacion:"Singular: 'a waiter'. Plural complement after 'are': 'cooks'." },
  { f:"2023-A", pregunta:"The man got a _____ for murder.", A:"life sentency", B:"perpetual punish", C:"life sentence", D:"permanent punish", correcta:"C", explicacion:"Fixed expression: 'life sentence' (cadena perpetua)." },
  // 2023 – Modelo B (página 18)
  { f:"2023-B", pregunta:"Frank _____ by a poisonous snake last week.", A:"would bitten", B:"was bitten", C:"was bit", D:"was bited", correcta:"B", explicacion:"Passive: was + bitten (past participle of bite)." },
  { f:"2023-B", pregunta:"Thomas is _____ he used to be.", A:"healthier that", B:"healthier than", C:"healthiest than", D:"more health than", correcta:"B", explicacion:"Comparative + than: 'healthier than'." },
  { f:"2023-B", pregunta:"She can speak 4 languages, _____?", A:"can't she", B:"doesn't she", C:"can't her", D:"does she", correcta:"A", explicacion:"Tag: 'can' → 'can't she'." },
  { f:"2023-B", pregunta:"Do you know _____?", A:"where are my glass", B:"where is my glasses", C:"where my glasses are", D:"where my glasses is", correcta:"C", explicacion:"Indirect question: statement word order." },
  { f:"2023-B", pregunta:"The book _____ I read last week was awesome!", A:"--", B:"who", C:"what", D:"whose", correcta:"A", explicacion:"Relative pronoun omitted in contact clause (object position)." },
  { f:"2023-B", pregunta:"I'm _____ but John and Louis are _____.", A:"a waiter / cooks", B:"a waiter / a cooks", C:"waiter / cook", D:"a waiters / cooks", correcta:"A", explicacion:"'A waiter' (singular). 'Cooks' (plural no article)." },
  { f:"2023-B", pregunta:"'Did you bring your waterproof jackets?' She asked them _____ waterproof jackets.", A:"whether they had bringed their", B:"if they bought their", C:"if they have brought my", D:"if they had brought their", correcta:"D", explicacion:"Reported question: past perfect. 'Your' → 'their'." },
  { f:"2023-B", pregunta:"When did you become a policewoman?", A:"From 5 years ago.", B:"Since 5 years ago.", C:"5 years ago.", D:"For 5 years ago.", correcta:"C", explicacion:"'When' → specific point → '5 years ago'." },
  { f:"2023-B", pregunta:"The man got a _____ for murder.", A:"life sentency", B:"perpetual punish", C:"life sentence", D:"permanent punish", correcta:"C", explicacion:"'Life sentence' = cadena perpetua." },
  { f:"2023-B", pregunta:"-_____ do you drink on a daily basis? -_____.", A:"How many water / A lots", B:"How much water / A lot", C:"How many waters / A lot", D:"How much water / Lot", correcta:"B", explicacion:"Uncountable → 'How much'. Answer: 'A lot'." },
  { f:"2023-B", pregunta:"If we _____ the lottery results in advance, we _____ rich!", A:"had know / would all be", B:"knew / would all been", C:"knew / would all be", D:"would known / had all be", correcta:"C", explicacion:"Second conditional: if + past simple / would + bare inf." },
  { f:"2023-B", pregunta:"The law firm is _____ the 7th floor, _____ the jewellery.", A:"on / near of", B:"in / near", C:"on / next to", D:"on / next of", correcta:"B", explicacion:"'On the 7th floor'. 'Near' (no 'of')." },
  { f:"2023-B", pregunta:"_____ several changes in the company.", A:"There have be", B:"There are been", C:"There have being", D:"There have been", correcta:"D", explicacion:"Present perfect: there + have been." },
  { f:"2023-B", pregunta:"Mr Smith _____ our company last year.", A:"refused join", B:"refused to join", C:"denied join", D:"denied to joining", correcta:"B", explicacion:"'Refuse' + to + infinitive." },
  { f:"2023-B", pregunta:"-How often _____ exercise? -_____.", A:"does Helen take / Once at week", B:"does take Helen / Once week", C:"has Helen take / One a week", D:"does Helen take / Twice a week", correcta:"D", explicacion:"Present simple for routines. 'Twice a week' is correct." },
  { f:"2023-B", pregunta:"_____, she had fastened her seat belt.", A:"Luckingly", B:"Luckly", C:"Luckedly", D:"Luckily", correcta:"D", explicacion:"Adverb: lucky → luckily." },
  { f:"2023-B", pregunta:"-Hey, look at that cave! -Wow! _____.", A:"How a beautiful!", B:"How beautiful!", C:"What beautiful!", D:"What a beautiful!", correcta:"B", explicacion:"'How + adjective' without a noun." },
  { f:"2023-B", pregunta:"I found two _____ dollars.", A:"hundred of", B:"hundreds of", C:"thousand of", D:"hundred", correcta:"D", explicacion:"Numbers: 'two hundred dollars' (no -s, no 'of')." },
  { f:"2023-B", pregunta:"The police officer _____ open the boot.", A:"told me to", B:"tell me to", C:"told to me", D:"said me to", correcta:"A", explicacion:"tell + object + to + infinitive." },
  { f:"2023-B", pregunta:"_____ a priest?", A:"How long have you been", B:"How long are you been", C:"How long have you being", D:"How many time have you been", correcta:"A", explicacion:"Present perfect for duration: 'How long have you been...?'" },
  // 2024 – Modelo A (páginas 18-19)
  { f:"2024-A", pregunta:"-What are you doing at the moment? -I _____ a novel. It _____ place in a foreign country.", A:"am writting / take", B:"am writing / takes", C:"write / is taking", D:"writing / takes", correcta:"B", explicacion:"Present continuous for current activity. 'Take place' 3rd person singular: takes." },
  { f:"2024-A", pregunta:"Which ones _____: the green or the _____ ones?", A:"are yours / yellow", B:"is yours / yellows", C:"are your / yellow", D:"are your / yellows", correcta:"A", explicacion:"'Which ones are yours' (plural). 'Yellow' as adjective: no plural." },
  { f:"2024-A", pregunta:"-How _____? -Nobody really _____.", A:"it happened / know", B:"did happen / knows", C:"happened / know", D:"did it happen / knows", correcta:"D", explicacion:"Past simple question: Did + subject + bare inf. 'Nobody knows' (nobody = singular)." },
  { f:"2024-A", pregunta:"The injuries are _____ I expected.", A:"worse of", B:"worse that", C:"worse than", D:"worser that", correcta:"C", explicacion:"Comparative + than: 'worse than' ('worse' is already the comparative of 'bad')." },
  { f:"2024-A", pregunta:"-How long _____ in Houston? -_____.", A:"do they lived / For 6 years", B:"have they lived / Since 6 years ago", C:"have they live / Since 2018", D:"have they lived / Since 2018", correcta:"D", explicacion:"Present perfect: 'have they lived'. 'Since 2018' = point in time." },
  { f:"2024-A", pregunta:"It _____ so nice! You _____ meet new people.", A:"will be / will be able to", B:"will being / will be able to", C:"will be / will able to", D:"will be / will can", correcta:"A", explicacion:"Future: will + bare infinitive. 'Will be able to' (future of can)." },
  { f:"2024-A", pregunta:"The performance was _____! I was so _____.", A:"amazing / excitement", B:"amazed / excited", C:"amazing / excited", D:"amazeing / excitated", correcta:"C", explicacion:"'Amazing' (active: describes thing). 'Excited' (passive: describes feeling)." },
  { f:"2024-A", pregunta:"The children hid under the table, _____?", A:"didn't they", B:"don't they", C:"weren't they", D:"didn't them", correcta:"A", explicacion:"'Hid' = past simple of hide → tag: 'didn't they'." },
  { f:"2024-A", pregunta:"When Sean arrived, he realized he _____ the present.", A:"forgotten", B:"had forgotten", C:"had forgot", D:"haved forgotten", correcta:"B", explicacion:"Past perfect for action before another past action: had + past participle." },
  { f:"2024-A", pregunta:"If you _____ his advice, you _____ better.", A:"follow / will fell", B:"will follow / will feel", C:"follow / will feel", D:"follow / will felt", correcta:"C", explicacion:"First conditional: if + present simple / will + bare infinitive." },
  { f:"2024-A", pregunta:"Maika can speak French _____.", A:"with fluently and with easily", B:"fluently and easily", C:"fluidity and easyly", D:"fluency and easily", correcta:"B", explicacion:"Adverbs: fluently and easily (both -ly)." },
  { f:"2024-A", pregunta:"The receptionist asked them: 'Have you stayed in this hotel before?' The receptionist asked them _____ hotel before.", A:"if they had stayed in these", B:"if they had stay in that", C:"if they had stayed in that", D:"wether they had stayed in that", correcta:"C", explicacion:"Reported speech: present perfect → past perfect. 'This' → 'that'." },
  { f:"2024-A", pregunta:"Luke and Mila enjoy _____ around the world.", A:"travelling", B:"travel", C:"to travel", D:"to travelling", correcta:"A", explicacion:"'Enjoy' is followed by a gerund (verb + -ing)." },
  { f:"2024-A", pregunta:"Be careful there! _____ snakes.", A:"There may to be", B:"There may been", C:"There may being", D:"There may be", correcta:"D", explicacion:"Modal + bare infinitive: 'there may be'." },
  { f:"2024-A", pregunta:"The Police say paintings worth millions of euros _____ yesterday from El Prado Museum.", A:"was stolen", B:"were stolen", C:"were stole", D:"had stolen", correcta:"B", explicacion:"Passive, plural: were + past participle (stolen)." },
  { f:"2024-A", pregunta:"Choose the best option.", A:"These children look hungry.", B:"These children looks hungry.", C:"This children look hungry.", D:"That children look hungry.", correcta:"A", explicacion:"'Children' is plural → 'these' + 'look' (no -s)." },
  { f:"2024-A", pregunta:"Mr. Salk was a medical researcher _____ developed the first effective vaccine for polio.", A:"whose", B:"--", C:"which", D:"who", correcta:"D", explicacion:"'Who' for people in subject position of a relative clause." },
  { f:"2024-A", pregunta:"This _____ Nico's backpack. It has his name inside.", A:"has be", B:"must be", C:"can't be", D:"might to be", correcta:"B", explicacion:"'Must be' expresses logical deduction (certainty)." },
  { f:"2024-A", pregunta:"I have _____ for you.", A:"a good news", B:"a good new", C:"goods news", D:"good news", correcta:"D", explicacion:"'News' is uncountable: no article, no plural." },
  { f:"2024-A", pregunta:"_____ to Egypt tomorrow morning on the 9 am flight.", A:"I'll flying", B:"I'm flying", C:"I'm going fly", D:"I going to fly", correcta:"B", explicacion:"Present continuous for planned future arrangements." },
  // 2024 – Modelo B (páginas 18-19)
  { f:"2024-B", pregunta:"Luke and Mila enjoy _____ around the world.", A:"travelling", B:"travel", C:"to travel", D:"to travelling", correcta:"A", explicacion:"'Enjoy' + gerund (verb -ing)." },
  { f:"2024-B", pregunta:"Mr. Salk was a medical researcher _____ developed the first effective vaccine for polio.", A:"whose", B:"--", C:"which", D:"who", correcta:"D", explicacion:"'Who' for people as subject of a relative clause." },
  { f:"2024-B", pregunta:"The performance was _____! I was so _____.", A:"amazing / excitement", B:"amazed / excited", C:"amazing / excited", D:"amazeing / excitated", correcta:"C", explicacion:"'Amazing' describes the thing. 'Excited' describes how the person feels." },
  { f:"2024-B", pregunta:"The receptionist asked them: 'Have you stayed in this hotel before?' The receptionist asked them _____ hotel before.", A:"if they had stayed in these", B:"if they had stay in that", C:"if they had stayed in that", D:"wether they had stayed in that", correcta:"C", explicacion:"Reported speech: present perfect → past perfect. 'This' → 'that'." },
  { f:"2024-B", pregunta:"I have _____ for you.", A:"a good news", B:"a good new", C:"goods news", D:"good news", correcta:"D", explicacion:"'News' is uncountable: 'good news'." },
  { f:"2024-B", pregunta:"-What are you doing at the moment? -I _____ a novel. It _____ place in a foreign country.", A:"am writting / take", B:"am writing / takes", C:"write / is taking", D:"writing / takes", correcta:"B", explicacion:"Present continuous. 'Take place': 3rd person takes." },
  { f:"2024-B", pregunta:"Choose the best option.", A:"These children look hungry.", B:"These children looks hungry.", C:"This children look hungry.", D:"That children look hungry.", correcta:"A", explicacion:"'Children' plural → 'these' + 'look'." },
  { f:"2024-B", pregunta:"-How _____? -Nobody really _____.", A:"it happened / know", B:"did happen / knows", C:"happened / know", D:"did it happen / knows", correcta:"D", explicacion:"Past simple question with inversion. 'Nobody knows' (3rd pers. sing.)." },
  { f:"2024-B", pregunta:"It _____ so nice! You _____ meet new people.", A:"will be / will be able to", B:"will being / will be able to", C:"will be / will able to", D:"will be / will can", correcta:"A", explicacion:"Future simple: will + bare infinitive. 'Will be able to' = future of can." },
  { f:"2024-B", pregunta:"When Sean arrived, he realized he _____ the present.", A:"forgotten", B:"had forgotten", C:"had forgot", D:"haved forgotten", correcta:"B", explicacion:"Past perfect: had + past participle." },
  { f:"2024-B", pregunta:"-How long _____ in Houston? -_____.", A:"do they lived / For 6 years", B:"have they lived / Since 6 years ago", C:"have they live / Since 2018", D:"have they lived / Since 2018", correcta:"D", explicacion:"Present perfect for duration. 'Since 2018' = point in time." },
  { f:"2024-B", pregunta:"If you _____ his advice, you _____ better.", A:"follow / will fell", B:"will follow / will feel", C:"follow / will feel", D:"follow / will felt", correcta:"C", explicacion:"First conditional: if + present simple / will + bare infinitive." },
  { f:"2024-B", pregunta:"This _____ Nico's backpack. It has his name inside.", A:"has be", B:"must be", C:"can't be", D:"might to be", correcta:"B", explicacion:"'Must be' = logical deduction (certeza)." },
  { f:"2024-B", pregunta:"_____ to Egypt tomorrow morning on the 9 am flight.", A:"I'll flying", B:"I'm flying", C:"I'm going fly", D:"I going to fly", correcta:"B", explicacion:"Present continuous for future arrangements." },
  { f:"2024-B", pregunta:"Maika can speak French _____.", A:"with fluently and with easily", B:"fluently and easily", C:"fluidity and easyly", D:"fluency and easily", correcta:"B", explicacion:"Adverbs: fluently and easily." },
  { f:"2024-B", pregunta:"The children hid under the table, _____?", A:"didn't they", B:"don't they", C:"weren't they", D:"didn't them", correcta:"A", explicacion:"Past simple → tag: 'didn't they'." },
  { f:"2024-B", pregunta:"Be careful there! _____ snakes.", A:"There may to be", B:"There may been", C:"There may being", D:"There may be", correcta:"D", explicacion:"Modal + bare infinitive: 'there may be'." },
  { f:"2024-B", pregunta:"The injuries are _____ I expected.", A:"worse of", B:"worse that", C:"worse than", D:"worser that", correcta:"C", explicacion:"Comparative: worse than." },
  { f:"2024-B", pregunta:"The Police say paintings worth millions of euros _____ yesterday from El Prado Museum.", A:"was stolen", B:"were stolen", C:"were stole", D:"had stolen", correcta:"B", explicacion:"Passive, plural: were + stolen." },
  { f:"2024-B", pregunta:"Which ones _____: the green or the _____ ones?", A:"are yours / yellow", B:"is yours / yellows", C:"are your / yellow", D:"are your / yellows", correcta:"A", explicacion:"'Which ones are yours'. 'Yellow' as adjective has no plural." },
  // 2025 simulacros
  { f:"2025-sim", pregunta:"How can you _____ that? I _______ lies.", A:"tell / don't say", B:"say / don't tell", C:"said / didn't tell", D:"say / don't told", correcta:"B", explicacion:"'Say' + content (no object). 'Tell' + person: 'I don't tell lies'." },
  { f:"2025-sim", pregunta:"The boss is the same age ________.", A:"as you", B:"as your", C:"that yours", D:"than you", correcta:"A", explicacion:"'The same … as' is the correct comparative structure." },
  { f:"2025-sim", pregunta:"My niece ________ off the bike yesterday and twisted ________ knee.", A:"falled / her", B:"feel / her", C:"fall / his", D:"fell / her", correcta:"D", explicacion:"Past simple of 'fall' = fell. Possessive 'her' agrees with 'niece'." },
  { f:"2025-sim", pregunta:"Tom ________ my call because he ________ a conversation with his boss.", A:"couldn't answered / is having", B:"didn't answered / was having", C:"didn't answer / was having", D:"didn't answer / had have", correcta:"C", explicacion:"'Didn't answer' (past simple neg.). 'Was having' (past continuous)." },
  { f:"2025-sim", pregunta:"The Police ________.", A:"have already block the road", B:"have blocked already the road", C:"have blocked the road yet", D:"have already blocked the road", correcta:"D", explicacion:"Present perfect: have + p.p. 'Already' before p.p." },
  { f:"2025-sim", pregunta:"She needs ________ for her office.", A:"some furniture", B:"some furnitures", C:"a lot of furnitures", D:"a lot furniture", correcta:"A", explicacion:"'Furniture' is uncountable. Use 'some furniture'." },
  { f:"2025-sim", pregunta:"We were ________ the tournament.", A:"the luckest team of", B:"the luckiest team in", C:"the luckiliest team in", D:"the luckyest team of", correcta:"B", explicacion:"Superlative: luckiest. Groups use 'in'." },
  { f:"2025-sim", pregunta:"I ________ contact you until Monday.", A:"won't can", B:"won't be able to", C:"won't able to", D:"will not be able", correcta:"B", explicacion:"Future of 'can': will be able to." },
  { f:"2025-sim", pregunta:"Robert ________ sick if he ________ so much junk food.", A:"wouldn't have felt / wouldn't eaten", B:"wouldn't have feel / hadn't eaten", C:"wouldn't have felt / hadn't eaten", D:"hadn't felt / hadn't ate", correcta:"C", explicacion:"Third conditional: would + have + p.p. / if + had + p.p." },
  { f:"2025-sim", pregunta:"Sam told her: 'Pass me the salt, please'. Turn into reported speech.", A:"Sam suggested pass her the salt.", B:"Sam asked to her to pass the salt, please.", C:"Sam asked her to passed him the salt.", D:"Sam asked her to pass him the salt.", correcta:"D", explicacion:"ask + object + to + infinitive. 'Me' → 'him'. No 'please'." },
  { f:"2025-sim", pregunta:"He hit the ball over the fence, ________?", A:"didn't he", B:"doesn't he", C:"wasn't he", D:"didn't him", correcta:"A", explicacion:"'Hit' past simple → tag: 'didn't he'." },
  { f:"2025-sim", pregunta:"You should call later, ________ some changes in the schedule.", A:"there might being", B:"there will been", C:"there will be", D:"there will have", correcta:"C", explicacion:"'There will be' = future of 'there is'." },
  { f:"2025-sim", pregunta:"The delay at the airport was really ________.", A:"frustrating", B:"frustate", C:"frustrated", D:"frustation", correcta:"A", explicacion:"Active participle '-ing' describes the cause of frustration." },
  { f:"2025-sim", pregunta:"Do you fancy ________ tonight? I think we deserve ________ fun.", A:"going out / to have", B:"go out / have", C:"to going out / having", D:"going out / to having", correcta:"A", explicacion:"'Fancy' + gerund. 'Deserve' + to + infinitive." },
  { f:"2025-sim", pregunta:"When did he ________ that? He ________ me anything.", A:"tell / didn't say", B:"say / didn't tell", C:"said / didn't tell", D:"say / don't told", correcta:"B", explicacion:"'Say' + content. 'Tell' + person: 'didn't tell me'." },
  { f:"2025-sim", pregunta:"You were ________ the truth eventually.", A:"bound discover", B:"bound to discovered", C:"bound of discovering", D:"bound to discover", correcta:"D", explicacion:"'Bound to' + bare infinitive = certain/destined to." },
  { f:"2025-sim", pregunta:"________ some relatives next weekend.", A:"I'll visiting", B:"I'm visiting", C:"I'm going visit", D:"I going to visit", correcta:"B", explicacion:"Present continuous for future plans." },
  { f:"2025-sim", pregunta:"He ________ admitted his mistake.", A:"with brave", B:"bravery", C:"bravely", D:"bravelily", correcta:"C", explicacion:"Adverb: brave → bravely." },
  { f:"2025-sim", pregunta:"After the tragedy, ________ patiently for assistance.", A:"these people waits", B:"that people wait", C:"this people waits", D:"these people wait", correcta:"D", explicacion:"'People' plural → 'these' + 'wait' (no -s)." },
  { f:"2025-sim", pregunta:"The results of the investigation ________ very soon.", A:"will be shared", B:"will be share", C:"will being shared", D:"it will be shared", correcta:"A", explicacion:"Future passive: will + be + past participle." },
];

// ══════════════════════════════════════════════════════════════════════
// FUNCIONES PÚBLICAS — generan exámenes aleatorios
// ══════════════════════════════════════════════════════════════════════

function getExamenOrtografia() {
  const frases = pickRandom(TODAS_FRASES_ORT, 10);
  return frases.map((f, i) => ({ ...f, num: i + 1 }));
}

function getExamenGramatica() {
  const preguntas = pickRandom(TODAS_PREGUNTAS_GRAM, 5);
  return preguntas.map((p, i) => ({ ...p, num: i + 1 }));
}

function getExamenIngles() {
  // Mezclar sin repetir la misma pregunta dos veces
  const preguntas = pickRandom(TODAS_PREGUNTAS_ING, 20);
  // Aleatorizar también el orden de las opciones dentro de cada pregunta
  return preguntas.map((p, i) => {
    const opciones = shuffle(['A','B','C','D']);
    const mapa = {};
    opciones.forEach((orig, idx) => { mapa[orig] = ['A','B','C','D'][idx]; });
    const newP = {
      num: i + 1,
      pregunta: p.pregunta,
      correcta: mapa[p.correcta],
      explicacion: p.explicacion,
      f: p.f,
    };
    ['A','B','C','D'].forEach((lbl, idx) => {
      newP[lbl] = p[opciones[idx]];
    });
    return newP;
  });
}

// ══════════════════════════════════════════════════════════════════════
// BANCO ADICIONAL — Más ejercicios para mayor variedad
// ══════════════════════════════════════════════════════════════════════

// Añadir al banco existente
TODAS_FRASES_ORT.push(
  // Frases extra ortografía — errores frecuentes en exámenes
  { f:"extra", texto_previo:"El", A:{word:"haministrador",error:true}, texto_AB:"firmó el", B:{word:"albalá",error:false}, texto_BC:"con total", C:{word:"indiferencia",error:false}, texto_CD:"ante los", D:{word:"testigos",error:false}, texto_post:".", explicacion:"A: 'haministrador' → 'administrador' (sin h inicial)." },
  { f:"extra", texto_previo:"La", A:{word:"absención",error:true}, texto_AB:"en las", B:{word:"urnas",error:false}, texto_BC:"fue", C:{word:"récord",error:false}, texto_CD:"este", D:{word:"año",error:false}, texto_post:".", explicacion:"A: 'absención' → 'abstención' (bt, no bs)." },
  { f:"extra", texto_previo:"El", A:{word:"yerno",error:false}, texto_AB:"llegó con su", B:{word:"suegra",error:false}, texto_BC:"y un", C:{word:"ramillete",error:false}, texto_CD:"de", D:{word:"gladiolos",error:false}, texto_post:".", explicacion:"Todas correctas." },
  { f:"extra", texto_previo:"El", A:{word:"vándalo",error:false}, texto_AB:"", B:{word:"rompió",error:false}, texto_BC:"el", C:{word:"cristal",error:false}, texto_CD:"de un", D:{word:"manotazo",error:false}, texto_post:".", explicacion:"Todas correctas." },
  { f:"extra", texto_previo:"La", A:{word:"exuberancia",error:false}, texto_AB:"de la", B:{word:"bellejación",error:true}, texto_BC:"vegetal", C:{word:"sorprendió",error:false}, texto_CD:"a los", D:{word:"excursionistas",error:false}, texto_post:".", explicacion:"B: 'bellejación' → 'vegetación' (error de concepto y ortografía)." },
  { f:"extra", texto_previo:"Necesitamos", A:{word:"proveer",error:false}, texto_AB:"de", B:{word:"víveres",error:false}, texto_BC:"al", C:{word:"destacamento",error:false}, texto_CD:"antes del", D:{word:"amaneser",error:true}, texto_post:".", explicacion:"D: 'amaneser' → 'amanecer' (c, no s)." },
  { f:"extra", texto_previo:"El", A:{word:"suboficial",error:false}, texto_AB:"redactó el", B:{word:"atestado",error:false}, texto_BC:"con", C:{word:"exaustividad",error:true}, texto_CD:"y lo", D:{word:"remitió",error:false}, texto_post:"al juzgado.", explicacion:"C: 'exaustividad' → 'exhaustividad' (exh-)." },
  { f:"extra", texto_previo:"La", A:{word:"bienvenida",error:false}, texto_AB:"al nuevo", B:{word:"recluta",error:false}, texto_BC:"fue", C:{word:"efusiba",error:true}, texto_CD:"y", D:{word:"emotiva",error:false}, texto_post:".", explicacion:"C: 'efusiba' → 'efusiva' (v, no b)." },
  { f:"extra", texto_previo:"El", A:{word:"agente",error:false}, texto_AB:"", B:{word:"interceptó",error:false}, texto_BC:"el", C:{word:"vehículo",error:false}, texto_CD:"en el", D:{word:"peage",error:true}, texto_post:".", explicacion:"D: 'peage' → 'peaje' (j)." },
  { f:"extra", texto_previo:"Los", A:{word:"detenidos",error:false}, texto_AB:"fueron", B:{word:"traladados",error:true}, texto_BC:"al", C:{word:"calabozo",error:false}, texto_CD:"de la", D:{word:"comisaría",error:false}, texto_post:".", explicacion:"B: 'traladados' → 'trasladados' (doble s: traslad-)." },
  { f:"extra", texto_previo:"La", A:{word:"amnistía",error:false}, texto_AB:"", B:{word:"benefició",error:false}, texto_BC:"a", C:{word:"numerozos",error:true}, texto_CD:"", D:{word:"presos",error:false}, texto_post:".", explicacion:"C: 'numerozos' → 'numerosos' (s, no z)." },
  { f:"extra", texto_previo:"El", A:{word:"forense",error:false}, texto_AB:"", B:{word:"certificó",error:false}, texto_BC:"el", C:{word:"óbito",error:false}, texto_CD:"a las", D:{word:"docehoras",error:true}, texto_post:".", explicacion:"D: 'docehoras' → 'doce horas' (dos palabras)." },
  { f:"extra", texto_previo:"La", A:{word:"benevolencia",error:false}, texto_AB:"del", B:{word:"magistrado",error:false}, texto_BC:"", C:{word:"sorprendió",error:false}, texto_CD:"a la", D:{word:"acusasión",error:true}, texto_post:".", explicacion:"D: 'acusasión' → 'acusación' (-ción)." },
  { f:"extra", texto_previo:"El", A:{word:"guardia",error:false}, texto_AB:"portaba su", B:{word:"arma",error:false}, texto_BC:"con", C:{word:"diligencia",error:false}, texto_CD:"y", D:{word:"precaución",error:false}, texto_post:".", explicacion:"Todas correctas." },
  { f:"extra", texto_previo:"La", A:{word:"excavación",error:false}, texto_AB:"", B:{word:"reveló",error:false}, texto_BC:"", C:{word:"vestigios",error:false}, texto_CD:"de una antigua", D:{word:"sivilización",error:true}, texto_post:".", explicacion:"D: 'sivilización' → 'civilización' (c, no s)." }
);

TODAS_PREGUNTAS_GRAM.push(
  // Gramática extra
  { f:"extra", A:"El agua estaba muy fría.", B:"Haiga quien haiga, entro yo primero.", C:"No me gusta que llegues tarde.", D:"Los niños se durmieron enseguida.", incorrectas:["B"], principal:"B", explicacion:"B: 'Haiga' no existe en español. La forma correcta es 'haya' (subjuntivo de haber)." },
  { f:"extra", A:"Te lo dije para que te enteraras.", B:"Espero de que vengas pronto.", C:"Me alegra que estés aquí.", D:"Es necesario que lo sepas.", incorrectas:["B"], principal:"B", explicacion:"B: dequeísmo. 'Espero de que' → 'Espero que'." },
  { f:"extra", A:"Se venden pisos.", B:"Se vende pisos.", C:"Se alquilan locales.", D:"Se necesitan empleados.", incorrectas:["B"], principal:"B", explicacion:"B: falta de concordancia. 'pisos' es plural → 'Se venden pisos'." },
  { f:"extra", A:"Cállate la boca.", B:"Sube arriba a por la maleta.", C:"El agente actuó con profesionalidad.", D:"La declaración fue tomada en tiempo y forma.", incorrectas:["A","B"], principal:"A", explicacion:"A: 'Cállate la boca' es redundante (pleonasmo): 'Cállate'. B: 'Sube arriba' es redundante: 'Sube a por la maleta'." },
  { f:"extra", A:"Fue él quien lo hizo.", B:"Entre tú y yo no hay secretos.", C:"Según tú, todo está bien.", D:"Hasta mí me parece excesivo.", incorrectas:["D"], principal:"D", explicacion:"D: 'Hasta mí' → 'Hasta a mí' (preposición 'a' necesaria con pronombre de primera persona)." },
  { f:"extra", A:"No sé si vendrá.", B:"Dime donde has puesto las llaves.", C:"¿Sabes cuándo llega el tren?", D:"No entiendo por qué lo hizo.", incorrectas:["B"], principal:"B", explicacion:"B: 'donde' en interrogativa indirecta lleva tilde: '¿Dime dónde has puesto las llaves?'" },
  { f:"extra", A:"Los alumnos aprobaron el examen.", B:"La gente estaban muy nerviosos.", C:"El equipo ganó el campeonato.", D:"La mayoría votó en contra.", incorrectas:["B"], principal:"B", explicacion:"B: 'La gente' es singular colectivo → 'estaba muy nerviosa'." },
  { f:"extra", A:"Me se cayó el móvil al suelo.", B:"Se me cayó el vaso.", C:"Se le olvidó el paraguas.", D:"Se nos acabó el tiempo.", incorrectas:["A"], principal:"A", explicacion:"A: 'Me se' → 'Se me' (el pronombre reflexivo 'se' siempre va antes)." },
  { f:"extra", A:"Le dije a María que viniera.", B:"La llamé por teléfono ayer.", C:"Le expliqué el problema detenidamente.", D:"La di un regalo por su cumpleaños.", incorrectas:["D"], principal:"D", explicacion:"D: laísmo. 'La di' → 'Le di' (complemento indirecto femenino)." },
  { f:"extra", A:"Prefiero que lo hagas tú.", B:"Ojalá llueva esta tarde.", C:"Quizás venga mañana.", D:"Tal vez vendrá o tal vez no.", incorrectas:[], principal:"", explicacion:"Todas las opciones son correctas gramaticalmente." },
  { f:"extra", A:"No hay ningún problema.", B:"Nunca jamás lo haré.", C:"No he visto a nadie.", D:"Tampoco lo sé yo.", incorrectas:["B"], principal:"B", explicacion:"B: 'Nunca jamás' es redundante (pleonasmo). Correcto: 'Nunca lo haré' o 'Jamás lo haré'." },
  { f:"extra", A:"El sargento y la cabo llegaron puntuales.", B:"Tanto él como ella estaban de acuerdo.", C:"Ni Juan ni Pedro sabían la respuesta.", D:"O tú o yo tenemos que ir.", incorrectas:[], principal:"", explicacion:"Todas son correctas." },
  { f:"extra", A:"Es una mujer muy trabajadora.", B:"Esa chica es muy buena persona.", C:"El problema está en que no escuchas.", D:"Es un chico muy listo e inteligente.", incorrectas:["D"], principal:"D", explicacion:"D: pleonasmo. 'Listo e inteligente' son sinónimos en este contexto. Aunque no es error gramatical grave, 'listo' aquí es redundante con 'inteligente'." },
  { f:"extra", A:"Voy a por el pan.", B:"El detenido fue puesto en libertad.", C:"Se lo dije de buenas maneras.", D:"Anduve todo el día de acá para allá.", incorrectas:[], principal:"", explicacion:"Todas son correctas." },
  { f:"extra", A:"Cometió el delito a sabiendas.", B:"Lo hizo adrede para perjudicarte.", C:"Actuó de motu proprio.", D:"Llegó el primero con diferencia.", incorrectas:["C"], principal:"C", explicacion:"C: 'motu proprio' → 'motu proprio' es correcto en latín, pero 'de motu proprio' lleva una 'de' incorrecta. La expresión es simplemente 'motu proprio'." }
);

TODAS_PREGUNTAS_ING.push(
  // Inglés extra — temas variados nivel A2-B1
  { f:"extra", pregunta:"She _____ to the gym three times a week.", A:"go", B:"goes", C:"is going", D:"going", correcta:"B", explicacion:"Present simple for habits/routines. 3rd person singular: goes." },
  { f:"extra", pregunta:"I haven't seen him _____ last Monday.", A:"for", B:"since", C:"ago", D:"during", correcta:"B", explicacion:"'Since' + specific point in time. 'For' + duration." },
  { f:"extra", pregunta:"By the time we arrived, the film _____.", A:"already started", B:"has already started", C:"had already started", D:"was already starting", correcta:"C", explicacion:"Past perfect for an action completed before another past action." },
  { f:"extra", pregunta:"You _____ smoke here. It's forbidden.", A:"mustn't", B:"needn't", C:"couldn't", D:"wouldn't", correcta:"A", explicacion:"'Mustn't' = prohibition. 'Needn't' = not necessary (different meaning)." },
  { f:"extra", pregunta:"The suspect _____ for hours when the detective arrived.", A:"has been questioned", B:"was being questioned", C:"had questioned", D:"questioned", correcta:"B", explicacion:"Past continuous passive for ongoing action at a past moment." },
  { f:"extra", pregunta:"_____ you mind opening the window?", A:"Will", B:"Shall", C:"Would", D:"Could", correcta:"C", explicacion:"'Would you mind + gerund' is a polite request." },
  { f:"extra", pregunta:"She asked me _____ I had seen her bag.", A:"if", B:"whether or not", C:"that", D:"what", correcta:"A", explicacion:"Reported yes/no questions use 'if' or 'whether'." },
  { f:"extra", pregunta:"He _____ be at home — his car is outside.", A:"must", B:"should", C:"might", D:"can", correcta:"A", explicacion:"'Must' for logical deduction (near certainty)." },
  { f:"extra", pregunta:"I'd rather you _____ tell anyone about this.", A:"don't", B:"won't", C:"didn't", D:"wouldn't", correcta:"C", explicacion:"'I'd rather + subject + past simple' for preference about someone else's action." },
  { f:"extra", pregunta:"The new law _____ into effect next month.", A:"comes", B:"will come", C:"is coming", D:"both B and C", correcta:"D", explicacion:"Both 'will come' (prediction) and 'is coming' (planned future) are correct here." },
  { f:"extra", pregunta:"Despite _____ hard, he failed the exam.", A:"study", B:"studied", C:"studying", D:"to study", correcta:"C", explicacion:"'Despite' + gerund (verb -ing)." },
  { f:"extra", pregunta:"The officer told the driver to pull _____.", A:"over", B:"out", C:"up", D:"off", correcta:"A", explicacion:"'Pull over' = stop the vehicle at the side of the road." },
  { f:"extra", pregunta:"No sooner _____ the alarm than everyone ran out.", A:"had rung", B:"rang", C:"had it rung", D:"it had rung", correcta:"C", explicacion:"'No sooner + inverted auxiliary + subject': 'No sooner had it rung'." },
  { f:"extra", pregunta:"She _____ used to living alone by now.", A:"got", B:"has got", C:"has gotten", D:"is", correcta:"B", explicacion:"'Have got used to' = be now accustomed to (present perfect)." },
  { f:"extra", pregunta:"The report needs _____ before tomorrow.", A:"finish", B:"to finish", C:"finishing", D:"finished", correcta:"C", explicacion:"'Need + gerund' (passive meaning: the report needs to be finished)." },
  { f:"extra", pregunta:"They _____ be twins — they look so alike.", A:"must", B:"should", C:"may", D:"can", correcta:"A", explicacion:"'Must' for strong logical deduction." },
  { f:"extra", pregunta:"I wish I _____ speak Spanish fluently.", A:"can", B:"could", C:"will", D:"would", correcta:"B", explicacion:"'I wish + past simple' for present wishes we can't fulfil." },
  { f:"extra", pregunta:"The thief _____ through the back window.", A:"broke in", B:"broke out", C:"broke up", D:"broke down", correcta:"A", explicacion:"'Break in' = enter by force." },
  { f:"extra", pregunta:"_____ the rain, the match continued.", A:"Despite of", B:"In spite", C:"Although", D:"Despite", correcta:"D", explicacion:"'Despite' + noun/gerund (no 'of'). 'In spite of' is correct with 'of'." },
  { f:"extra", pregunta:"How _____ sugar do you take in your coffee?", A:"many", B:"much", C:"lot of", D:"few", correcta:"B", explicacion:"'Sugar' is uncountable → 'how much'." },
  { f:"extra", pregunta:"By 2030, scientists _____ a cure for the disease.", A:"will find", B:"will have found", C:"are finding", D:"find", correcta:"B", explicacion:"Future perfect for action completed before a future point." },
  { f:"extra", pregunta:"It's time you _____ your homework.", A:"do", B:"did", C:"have done", D:"will do", correcta:"B", explicacion:"'It's time + subject + past simple' for actions overdue." },
  { f:"extra", pregunta:"She _____ rather stay home than go to the party.", A:"will", B:"should", C:"would", D:"could", correcta:"C", explicacion:"'Would rather + bare infinitive' for preference." },
  { f:"extra", pregunta:"The police officer _____ his badge to identify himself.", A:"showed", B:"shown", C:"was showing", D:"shows", correcta:"A", explicacion:"Past simple for completed action in a past narrative." },
  { f:"extra", pregunta:"We need to look _____ this matter more carefully.", A:"at", B:"for", C:"after", D:"into", correcta:"D", explicacion:"'Look into' = investigate." }
);
